### PR TITLE
Fix future queries with non lazy associations

### LINKED ISSUE #2173: Futures not batching correctly in NH 5.2.x
While attempting to upgrade from NH 5.1.3 to 5.2.5, we have a performance test that started failing relating to batching of `.Future()` queries. The following test passed as expected in NH 5.1.3, but is now failing in NH 5.2.5 with a statement count of 11(!). I've verified the NH statement statistic count is correct from observing commands issued in the Npgsql driver log.

```csharp
long preRequestPrepareStatementCount = _sessionFactory.Statistics.PrepareStatementCount;

session.QueryOver<VolumeAttachment>()
    .Where(va => va.Id.IsIn(volumeAttachmentIds))
    .Left.JoinQueryOver(va => va.StatusConditions)
    .Future();

session.QueryOver<VolumeAttachment>()
    .Where(va => va.Id.IsIn(volumeAttachmentIds))
    .Left.JoinQueryOver<VolumeAttachmentPath>(va => va.VolumeAttachmentPaths)
    .Left.JoinQueryOver(vap => vap.StatusConditions)
    .Future();

session.QueryOver<VolumeAttachment>()
    .Where(va => va.Id.IsIn(volumeAttachmentIds))
    .Left.JoinQueryOver<VolumeAttachmentPath>(va => va.VolumeAttachmentPaths)
    .Left.JoinQueryOver(vap => vap.Path)
    .Left.JoinQueryOver(p => p.StatusConditions)
    .Future();

session.QueryOver<VolumeAttachment>()
    .Where(va => va.Id.IsIn(volumeAttachmentIds))
    .Left.JoinQueryOver<VolumeAttachmentPath>(va => va.VolumeAttachmentPaths)
    .Left.JoinQueryOver(vap => vap.Path)
    .Left.JoinQueryOver(p => p.TargetPorts)
    .Future()
    .GetEnumerable();

long prepareStatementDelta = _sessionFactory.Statistics.PrepareStatementCount - preRequestPrepareStatementCount;

Assert.Equals(1, prepareStatementDelta);
```

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #2173 (some technical details behind this issue can be  found [here](https://github.com/nhibernate/nhibernate-core/issues/2173#issuecomment-501019937))

Implemented the following fix:
* Moved actual collection initialization logic after all queries are processed (as it's done in legacy `MultiCriteriaImpl`/`MultiQueryImpl`)
* Introduced `LoadingCollectionEntry.StopLoading` flag that indicates that collection should not be populated. This allows to delay actual collection initialization till all other batch queries are processed (so it's a fix for #1293)
 
Issue is introduced in 5.2 with new `QueryBatch` implementation.

### CODE REVIEW

**Comment by bahusoid** [comment]
Added some preliminary work on possible fix. TODO: Investigate what's wrong with cacheable future queries with this fix

File: src/NHibernate/Async/Multi/QueryBatch.cs [hunk 1]
```diff
@@ -139,33 +139,29 @@ protected async Task ExecuteBatchedAsync(CancellationToken cancellationToken)
...
 				{
+					cacheBatcher = new CacheBatcher(Session);
 					using (var reader = await (resultSetsCommand.GetReaderAsync(Timeout, cancellationToken)).ConfigureAwait(false))
 					{
-						var cacheBatcher = new CacheBatcher(Session);
 						foreach (var query in _queries)
 						{
 							if (query.CachingInformation != null)
 							{
-								foreach (var cachingInfo in query.CachingInformation.Where(ci => ci.IsCacheable))
```
Comment (bahusoid) [inline src/NHibernate/Async/Multi/QueryBatch.cs]: `cacheBatcher` is also needed when query is not cacheable but loaded entities are cacheable - so it's better to always set it.

**Comment by hazzik** [comment]
@bahusoid is it regression? If so, could you please re-target to 5.2.x?

File: src/NHibernate/Async/Multi/QueryBatchItemBase.cs [hunk 2]
```diff
@@ -103,7 +103,7 @@ public async Task<int> ProcessResultsSetAsync(DbDataReader reader, CancellationT
 
 					queryInfo.Result = tmpResults;
 					if (queryInfo.CanPutToCache)
-						queryInfo.ResultToCache = tmpResults;
+						queryInfo.ResultToCache = new List<object>(tmpResults);
```
Comment (bahusoid) [inline src/NHibernate/Async/Multi/QueryBatchItemBase.cs]: When merging to master this change should be ignored. The following code is expected in master:
```C#
queryInfo.ResultToCache = queryCacheBuilder.Result;
```
