### PR TITLE
Join-fetching with property-ref results in select n+1

### LINKED ISSUE #1226: NH-2534 - Join-fetching a many-to-one with property-ref results in select n+1 problem
**cremor** created an [issue](https://nhibernate.jira.com/browse/NH-2534) — <time datetime="2011-02-07T00:58:25.966Z" title="2011-02-07T00:58:25.966Z">7th February 2011, 0:58:25</time>:
> The attached test shows that a `many-to-one` association referencing an unique property (instead of the Id) results in a select n+1 problem. Although the first statement contains the correct join, all associated entities are fetched one by one after the join select. (Entities with the same value in the unique column are even fetched more than once.)
> 
> The interesting point is that this bug only occurs if the referenced entities are already in the session cache. If they are not, no additional select statements are created.
> 
---
**Keith Shannon** added a comment — <time datetime="2011-03-11T13:35:09.298Z" title="2011-03-11T13:35:09.298Z">11th March 2011, 13:35:09</time>:
> I was also able to reproduce this issue in NH 2.1.2, so it's a long-standing issue with join fetching.
> 
---
**Johan Haest** added a comment — <time datetime="2013-11-27T09:38:20.233Z" title="2013-11-27T09:38:20.233Z">27th November 2013, 9:38:20</time>:
> Any workarounds yet? Or even fixes?
> 
---
**Kamil Kliczbor** added a comment — <time datetime="2013-11-29T08:48:41.484Z" title="2013-11-29T08:48:41.484Z">29th November 2013, 8:48:41</time>:
> <~johanhaest>: we had the same issue in our project. The symptom was the same. Finally we gave up with the property-ref reference and switched to normal foreign key relationship (it was possible). And I think that solution is not so trivial.
> 
---
**Johan Haest** added a comment — <time datetime="2013-11-29T09:14:51.185Z" title="2013-11-29T09:14:51.185Z">29th November 2013, 9:14:51</time>:
> Not when your join is not on the primary key of the many to one class right?
> 
---
**Kamil Kliczbor** added a comment — <time datetime="2013-11-29T10:46:28.544Z" title="2013-11-29T10:46:28.544Z">29th November 2013, 10:46:28</time>:
> Right. We had join to other column that Id, but under certain circumstances we could abandon this approach.
>

### PR DESCRIPTION
**Pull request by fredericDelaporte**
* Fixes #1226 (NH-2534)

This is a rebase of #1460, with async regen, squashed, as it was asked [here](https://github.com/nhibernate/nhibernate-core/pull/1460#issuecomment-350706536).

### CODE REVIEW

File: src/NHibernate/Loader/Loader.cs [hunk 1]
```diff
@@ -972,6 +972,29 @@ private void CheckVersion(int i, IEntityPersister persister, object id, object e
 					entry.LockMode = lockMode;
 				}
 			}
+
+			// #1226: If it is already loaded and can be loaded from an association with a property ref, make
```
Comment (hazzik) [inline src/NHibernate/Loader/Loader.cs]: Can this please be extracted into an own method?

**Comment by hazzik** [comment]
@fredericDelaporte why not do it in the original PR? It seems to have "changes from contributors" enabled.

**Comment by fredericDelaporte** [comment]
> It seems to have "changes from contributors" enabled.

Yes but I have seen on some other PR that some people have difficulties handling forced pushes, so unless the contributor has already shown by its action on his PR that it is not a trouble for him, I now avoid doing forced pushes on their PR.

File: src/NHibernate/Loader/Loader.cs (hunk 1 above)
Comment (fredericDelaporte) [reply src/NHibernate/Loader/Loader.cs]: Done.

**Comment by gliljas** [comment]
@fredericDelaporte Yes, force pushing on someone else's PR should only be done after communicating with the owner about it.

**Comment by hazzik** [comment]
@fredericDelaporte can the CacheByUniqueKey logic be unifed, eg. called this way:

```
//If the object is already loaded, return the loaded one
obj = session.GetEntityUsingInterceptor(key);
if (obj != null)
{
	//its already loaded so dont need to hydrate it
	InstanceAlreadyLoaded(rs, i, persisters[i], key, obj, lockModes[i], session);
}
else
{
	obj = InstanceNotYetLoaded(rs, i, persisters[i], key, lockModes[i], descriptors[i].RowIdAlias, optionalObjectKey, optionalObject, hydratedObjects, session);
}
CacheByUniqueKey(i, persisters[i], obj, session);
```

And remove this logic from `LoadFromResultSet`?

**Comment by fredericDelaporte** [comment]
> can the CacheByUniqueKey logic be unifed

No, there is a trap here: in the `InstanceNotYetLoaded` case, `obj` is not actually hydrated but just put in a "to be hydrated" list, with its `values` array already put in persistence context. So getting its unique key value from its properties as do `CacheByUniqueKey` will fail. We may try to get `values` back from the persistence context in such case, but this would cause a more complex code and also more redundant unique key caching when the entity appears in many rows.

**Comment by hazzik** [comment]
I've discovered this "trap". 

this code works:

```csharp
obj = session.GetEntityUsingInterceptor(key);
var persister = persisters[i];
object[] values;
if (obj != null)
{
	//its already loaded so dont need to hydrate it
	InstanceAlreadyLoaded(rs, i, persister, key, obj, lockModes[i], session);
	values = persister.GetPropertyValues(obj);
	CacheByUniqueKey(i, persister, obj, session, values);
}
else
{
	obj = InstanceNotYetLoaded(rs, i, persister, key, lockModes[i], descriptors[i].RowIdAlias, optionalObjectKey, optionalObject, hydratedObjects, session);
	var entry = session.PersistenceContext.GetEntry(obj);
	values = entry.LoadedState;
}
CacheByUniqueKey(i, persister, obj, session, values);
```

File: src/NHibernate/Loader/Loader.cs [hunk 2]
```diff
@@ -972,6 +972,34 @@ private void CheckVersion(int i, IEntityPersister persister, object id, object e
...
 			}
+
+			CacheByUniqueKey(i, persister, obj, session);
+		}
+
+		private void CacheByUniqueKey(int i, IEntityPersister persister, object obj, ISessionImplementor session)
+		{
+			// #1226: If it is already loaded and can be loaded from an association with a property ref, make
+			// sure it is also cached by its unique key.
+			var ukName = OwnerAssociationTypes?[i]?.RHSUniqueKeyPropertyName;
```
Comment (hazzik) [inline src/NHibernate/Loader/Loader.cs]: can we unfold `?` operator here? It looks unreadable.

File: src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+		protected override void OnTearDown()
+		{
+			base.OnTearDown();
+
+			using (var session = OpenSession())
+			{
+				using (var tx = session.BeginTransaction())
+				{
+					session.Delete("from Account");
+					session.Delete("from Bank");
```
Comment (hazzik) [inline src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: `CreateQuery("delete ...").ExecuteUpdate()`?

File: src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+			}
+		}
+
+		protected override void OnTearDown()
+		{
+			base.OnTearDown();
+
+			using (var session = OpenSession())
+			{
+				using (var tx = session.BeginTransaction())
```
Comment (hazzik) [inline src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: please align nested usings:

```
using(...)
using(...)
[
}
```

File: src/NHibernate.Test/Async/NHSpecificTest/GH1226/Fixture.cs [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+	[TestFixture]
+	public class FixtureAsync : BugTestCase
+	{
+		protected override void OnSetUp()
+		{
+			base.OnSetUp();
+
+			using (var session = OpenSession())
+			{
+				using (var tx = session.BeginTransaction())
```
Comment (hazzik) [inline src/NHibernate.Test/Async/NHSpecificTest/GH1226/Fixture.cs]: Same

File: src/NHibernate/Loader/Loader.cs [hunk 6]
```diff
@@ -972,6 +972,34 @@ private void CheckVersion(int i, IEntityPersister persister, object id, object e
...
+			//    is a second case, just test for ukValue null.
+			//  - Entity association is unset in session but not yet persisted, autoflush disabled: ignore. We are
+			//    already in an error case: querying entities changed in session without flushing them before querying.
+			//    So here it gets loaded as if it were still associated, but we do not have the key anymore in session:
+			//    we cannot cache it, so long for the additionnal round-trip this will cause. (Do not fallback on
+			//    reading the key in rs, this is stale data in regard to the session state.)
+			if (ukValue == null)
+				return;
+			var type = persister.PropertyTypes[index];
+			var euk = new EntityUniqueKey(persister.EntityName, ukName, ukValue, type, session.Factory);
```
Comment (hazzik) [inline src/NHibernate/Loader/Loader.cs]: LoadFromRow's version caches by rootPersister.EntityName. Please add a test where the referenced entity is a hierarchical object.

File: src/NHibernate/Loader/Loader.cs (hunk 2 above)
Comment (fredericDelaporte) [reply src/NHibernate/Loader/Loader.cs]: Just null propagation all the way. Original code was:
```c#
IAssociationType[] ownerAssociationTypes = OwnerAssociationTypes;
if (ownerAssociationTypes != null && ownerAssociationTypes[i] != null)
{
	string ukName = ownerAssociationTypes[i].RHSUniqueKeyPropertyName;
```

Would you rather have:
```c#
var ownerAssociationTypes = OwnerAssociationTypes;
if (ownerAssociationTypes == null)
	return;
var ukName = ownerAssociationTypes[i]?.RHSUniqueKeyPropertyName;
```

File: src/NHibernate/Loader/Loader.cs (hunk 6 above)
Comment (fredericDelaporte) [reply src/NHibernate/Loader/Loader.cs]: Here `persister` is `rootPersister`. Non-root `persister` is a thing existing only inside `LoadFromResultSet`.

**Comment by fredericDelaporte** [comment]
> this code works:

But it causes, in the already loaded case, to get all the entity properties from its tuplizer even if there is no unique key, which is quite heavier than getting only one property when there is an unique key. I would rather pass `null` as `values` for this case, and fallback on the single property.
Well I consider instead passing an `alreadyLoaded` boolean and handle that inside the method.

File: src/NHibernate/Loader/Loader.cs (hunk 6 above)
Comment (hazzik) [reply src/NHibernate/Loader/Loader.cs]: Ok

File: src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+		}
+
+		[Test]
+		public void BankShouldBeJoinFetched()
+		{
+			using (var session = OpenSession())
+			using (var tx = session.BeginTransaction())
+			{
+				// Bug only occurs if the Banks are already in the session cache.
+				session.CreateQuery("from Bank").List<Bank>();
```
Comment (hazzik) [inline src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: Since the old code has changed, could this case please be checked as well?

File: src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+			Sfi.Statistics.IsStatisticsEnabled = true;
+		}
+
+		[Test]
+		public void BankShouldBeJoinFetched()
+		{
+			using (var session = OpenSession())
+			using (var tx = session.BeginTransaction())
+			{
+				// Bug only occurs if the Banks are already in the session cache.
```
Comment (hazzik) [inline src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: Since the old code has changed, could this case please be checked as well?

Comment (fredericDelaporte) [reply src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: You mean, checking eager fetching works for `Bank` not already in session too? It is likely this is already tested somewhere else, but why not.

Comment (fredericDelaporte) [reply src/NHibernate.Test/NHSpecificTest/GH1226/Fixture.cs]: Done.
