### PR TITLE
Fix TypeLoadException in StaticProxyFactory when class has not visible interfaces

### LINKED ISSUE #1643: Exception after upgrading to 5.1.0
Hi,
upgrading the following packages:
NHibernate 5.0.3 -> 5.1.0
Iesi.Collections 4.0.3 -> 4.0.4
Remotion.Linq.EagerFetching 2.1.0 -> 2.2.0
breaks my application (.NET 4.7, Nhibernate, Nhibernate Validator, NHibernate.AspNet.Identity).

The exception is the following

> 2018-04-06 10:57:25,821 [83] ERROR NHibernate.Proxy.StaticProxyFactory - Creating a proxy instance failed
System.TypeLoadException: Type 'ApplicationUserProxy' from assembly 'ApplicationUserProxyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at NHibernate.Proxy.NHibernateProxyBuilder.CreateProxyType(Type baseType, IReadOnlyCollection`1 baseInterfaces)
   at NHibernate.Proxy.StaticProxyFactory.CreateProxyActivator(ProxyCacheEntry pke)
   at NHibernate.Proxy.StaticProxyFactory.<GetProxy>b__2_0(ProxyCacheEntry pke)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NHibernate.Proxy.StaticProxyFactory.GetProxy(Object id, ISessionImplementor session)
2018-04-06 10:57:25,852 [83] ERROR MyProject.Domain.UnitOfWork.Factory.UnitOfWorkFactory - NHibernate.HibernateException: Creating a proxy instance failed ---> System.TypeLoadException: Type 'ApplicationUserProxy' from assembly 'ApplicationUserProxyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at NHibernate.Proxy.NHibernateProxyBuilder.CreateProxyType(Type baseType, IReadOnlyCollection`1 baseInterfaces)
   at NHibernate.Proxy.StaticProxyFactory.CreateProxyActivator(ProxyCacheEntry pke)
   at NHibernate.Proxy.StaticProxyFactory.<GetProxy>b__2_0(ProxyCacheEntry pke)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NHibernate.Proxy.StaticProxyFactory.GetProxy(Object id, ISessionImplementor session)
   --- End of inner exception stack trace ---
   at NHibernate.Proxy.StaticProxyFactory.GetProxy(Object id, ISessionImplementor session)
   at NHibernate.Tuple.Entity.AbstractEntityTuplizer.CreateProxy(Object id, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.CreateProxy(Object id, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.CreateProxyIfNecessary(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options, IPersistenceContext persistenceContext)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object value, ISessionImplementor session, Object owner)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister)
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId)
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Load(Object id, Object optionalObject, LockMode lockMode, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.DoLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.Get(String entityName, Object id)
   at NHibernate.Impl.SessionImpl.Get[T](Object id)
   at MyProject.Domain.Repository.BaseRepository`2.GetById(TKey id) in C:\Users\Matteo\Documents\Projects\MyProject\MyProject.Domain\Repository\BaseRepository.cs:line 18
   at MyProject.Services.Implementations.RefreshTokenService.<>c__DisplayClass2_0.<GetToken>b__0(IBaseUnitOfWork uok, IRepositoryFactory repoFactory) in C:\Users\Matteo\Documents\Projects\MyProject\MyProject.Services\Implementations\RefreshTokenService.cs:line 50
   at MyProject.Domain.UnitOfWork.Factory.BaseUnitOfWorkFactory.Create(Action`2 action, Func`2 exceptionHandling) in C:\Users\Matteo\Documents\Projects\MyProject\MyProject.Domain\UnitOfWork\Factory\UnitOfWorkFactory.cs:line 28

The ApplicationUser entity is
`
public class ApplicationUser : NHibernate.AspNet.Identity.IdentityUser
{
//my properties
}
`

Everything is working correctly with 5.0.3.
I didn't find anything useful in the release notes, is there something that needs to be changed or looked at when upgrading to 5.1?

Thanks in advance

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #1643

### CODE REVIEW

File: src/NHibernate/Proxy/NHibernateProxyBuilder.cs [hunk 1]
```diff
@@ -74,6 +74,8 @@ public TypeInfo CreateProxyType(System.Type baseType, IReadOnlyCollection<System
 				interfaces.Add(baseType);
 			}
 
+			interfaces.RemoveWhere(i => !i.IsVisible);
+
```
Comment (fredericDelaporte) [inline src/NHibernate/Proxy/NHibernateProxyBuilder.cs]: Shouldn't it emit a warning there?
It is not the dynamic proxy (which should be removed once lazy properties are handled by static proxies).

Something like "Interface {0} is not accessible, its members will not be proxified for entity {0}. If they access directly some internal state of the entity, unexpected outcome may occur.".

Due to the way NHibernate's proxies work, it could even be considered that trying to proxify entities implementing some internal interfaces is an error. But since the old proxies were not detecting the case and were letting silently these members unproxified, it would be a breaking change doable only for 6.0.

(It is an error because if some proxy instance is given back to some methods of the assembly holding the internal interfaces, it may call those methods. If they access directly internal or private state, they will then access the inherited proxy state instead of the delegated entity state handled by the proxy.)

Comment (fredericDelaporte) [reply src/NHibernate/Proxy/NHibernateProxyBuilder.cs]: Well, the error case would also require, for actually being an error, to have these methods explicitly implemented. So unless this additional condition can be reliably detected, it should not be rejected as an error.

Comment (hazzik) [reply src/NHibernate/Proxy/NHibernateProxyBuilder.cs]: I don't think we need any warnings here.

Comment (hazzik) [reply src/NHibernate/Proxy/NHibernateProxyBuilder.cs]: I don't think that any warning necessary

**Comment by hazzik** [comment]
There is a possibility to improve that behaviour 

1. Detect that assembly has `InternalsVisibleToAttribute` pointing to the assembly containing static proxy (it will require to settle the assembly name, as now it's dynamic).
2. The problem with nested classes and interfaces - it is hard to properly identify if the class would be actually visible if `InternalsVisibleToAttribute` applies. To properly detect that it would require to traverse the nesting tree. 
4. Emit warning once per proxy type suggesting to make interfaces public or apply `InternalsVisibleToAttribute`.

**Comment by fredericDelaporte** [comment]
I am not really convinced it is worth bothering with [`InternalsVisibleToAttribute`](https://docs.microsoft.com/fr-fr/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute). It works only if both assemblies are signed, or both unsigned.

And well, the interface being internal is not a trouble if none of its members is declared explicitly: they will then be proxified as public virtual members of the class. It is only if the interface is internal and if some of its members are explicitly implemented that a trouble can occur, because those members will not be proxified. (But if their implementations only use other visible members, proxified, then it will still not cause any trouble.)

**Comment by hazzik** [comment]
Agree

> It works only if both assemblies are signed, or both unsigned.

We could build either signed (with known key) or unsigned assembly depending on the circumstances, it should not be a problem.
