### PR TITLE
Fix Linq Fetch over component after fetching an association

### LINKED ISSUE #2511: Linq Fetch over component after fetching a many-to-one throws exception
I have a Linq query that looks like this:

    session.Query<MyEntity>()
        .Fetch(x => x.UnrelatedManyToOneProperty)
        .Fetch(x => x.ComponentProperty).ThenFetch(x => x.ManyToOneInComponent)
        .Where(x => x.Id == someId)
        .ToArray();

This query worked in NHibernate 5.2.7 (although it didn't actually fetch the many-to-one in the component, see #1232). But with NHibernate 5.3.2 this query now throws an exception:

    InvalidOperationException: Property x.ComponentProperty does not exist on entity TypeOfUnrelatedManyToOneProperty
       at NHibernate.Persister.Entity.AbstractEntityPersister.PropertySelectFragment(String name, String suffix, ICollection`1 fetchProperties, Boolean allProperties)

If I remove the `.Fetch(x => x.UnrelatedManyToOneProperty)` part of the query it works (and even correctly fetches the many-to-one in the component, which means that #1232 was fixed, except that we now have this regression).

### PR DESCRIPTION
**Pull request by maca88**
Fix a regression made by #1922.

Fixes #2511

### CODE REVIEW

File: src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs [hunk 1]
```diff
@@ -61,20 +82,21 @@ private void Process(FetchRequestBase resultOperator, QueryModelVisitor queryMod
...
+						Process(innerFetch, queryModelVisitor, tree, memberPath, currentNode, componentType.Subtypes[subTypeIndex]);
 					}
 
 					return;
 				}
 			}
 
 			var alias = queryModelVisitor.Model.GetNewName("_");
-			tree.AddFromClause(tree.TreeBuilder.LeftFetchJoin(memberPath, tree.TreeBuilder.Alias(alias)));
+			currentNode = tree.TreeBuilder.LeftFetchJoin(memberPath, tree.TreeBuilder.Alias(alias));
```
Comment (hazzik) [inline src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs:93]: For the `FetchManyRequest` the `currentNode` is always set, so the null check above does not matter.

File: src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs [hunk 2]
```diff
@@ -19,16 +19,37 @@ public void Process(FetchRequestBase resultOperator, QueryModelVisitor queryMode
 		}
 
 		public void Process(FetchRequestBase resultOperator, QueryModelVisitor queryModelVisitor, IntermediateHqlTree tree, string sourceAlias)
+		{
+			Process(resultOperator, queryModelVisitor, tree, tree.GetFromRangeClause(), sourceAlias);
+		}
+
+		public void Process(
```
Comment (hazzik) [inline src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs:26]: Can this be private please?

File: src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs (hunk 1 above)
Comment (bahusoid) [reply src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs:93]: It seems not only `FetchManyRequest` but all fetch requests except components.

That got me thinking that `tree.GetFromRangeClause()` call should be moved inside component block as it's the only case it's needed.

File: src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs (hunk 2 above)
Comment (bahusoid) [reply src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs]: Done

File: src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs (hunk 1 above)
Comment (maca88) [reply src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs:94]: It is required only for property fetching so that the node is added to the correct from/join node. The applied change is valid, so I am marking this as resolved.

**Review by bahusoid — APPROVED** [review]
