### PR TITLE
Fix decimal equality comparison for Sqlite

### LINKED ISSUE #2792: Arithmetic operations adding casts to SQLite that cause incorrect results
Affects v5.3.0+

*How to Reproduce*
`var result = session.Query<Entity>().Where(e => e.DecimalValue != null && (offset + e.DecimalValue) == test).ToList();`
`var result = session.Query<Entity>().Where(e => e.IntValue != null && (offset + (decimal?)e.IntValue) == test).ToList();`

Where `offset` and `test` are `decimal` or `decimal?` types.

*Expected Result*
`result` contains a list of entities where the equality condition matches.
This works fine for PostgreSQL and MS SQL Server.

*Actual Result*
SQLite gives no errors and always produces 0 results.

### PR DESCRIPTION
**Pull request by maca88**
It is a fix for a regression made by #2335.

Fixes #2792

### CODE REVIEW

File: src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs [hunk 1]
```diff
@@ -579,8 +579,12 @@ protected HqlTreeNode VisitConstantExpression(ConstantExpression expression)
 			if (_parameters.ConstantToParameterMap.TryGetValue(expression, out namedParameter))
 			{
 				_parameters.RequiredHqlParameters.Add(new NamedParameterDescriptor(namedParameter.Name, null, false));
+				var parameter = _hqlTreeBuilder.Parameter(namedParameter.Name).AsExpression();
 
-				return _hqlTreeBuilder.Parameter(namedParameter.Name).AsExpression();
+				// SQLite driver binds decimal parameters to text, which can cause unexpected results in arithmetic operations.
+				return expression.Type.UnwrapIfNullable() == typeof(decimal) && _parameters.SessionFactory.Dialect.IsDecimalStoredAsFloatingPointNumber
```
Comment (bahusoid) [inline src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs:585]: Better swap those checks... Also maybe make `IsDecimalStoredAsFloatingPointNumber` public and use in tests instead of Dialect checks.

Comment (maca88) [reply src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs]: Done.

**Review by bahusoid — APPROVED** [review]
Why WIP? Fix looks complete to me

**Comment by maca88** [comment]
I forgot to remove it.
