### PR TITLE
Fix transaction leak

### LINKED ISSUE #2144: AdoTransaction memory leak (5.2.5)
I'm investigation memory leak in my project. I found one of memory leak reasons inside NHibernate assembly. AdoTransaction objects created in NHibernate.AdoNet.AbstractBatcher.Prepare() via accessing property NHibernate.AdoNet.ConnectionManager.Transaction are not disposing.

image

So i tried to fix it.

First change in NHibernate\Transaction\AdoTransaction.cs
image

Second change in NHibernate\AdoNet\ConnectionManager.cs 
image

I'm not sure that thouse changes are correct but now all work fine. Can you check it?

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Fixes #2144

Instead of disposing `ConnectionManager._transaction` in `AfterTransaction` as proposed in #2144, this obsoletes `ConnectionManager.Transaction` in favor of a new `ConnectionManager.CurrentTransaction` property which does not create a transaction when none are already created, but yields `null`.

So now any existing transaction should be the result of a call to `BeginTransaction`, and its disposal is always a responsibility of the caller.

### CODE REVIEW

File: src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs [hunk 1]
```diff
@@ -188,9 +188,9 @@ protected virtual void DropTemporaryTableIfNecessary(IQueryable persister, ISess
 			{
 				IIsolatedWork work = new TmpIdTableDropIsolatedWork(persister, log, session);
 
-				if (ShouldIsolateTemporaryTableDDL())
+				if (ShouldIsolateTemporaryTableDDL() && session.ConnectionManager.CurrentTransaction != null)
 				{
-					session.ConnectionManager.Transaction.RegisterSynchronization(
+					session.ConnectionManager.CurrentTransaction.RegisterSynchronization(
```
Comment (fredericDelaporte) [inline src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: This is a "side" bug-fix indeed. The temporary table would never have been dropped previously, in case the operation occurred outside of a transaction. The NHibernate transaction would have received the drop to do "after transaction", but the synchs are executed only on actual commit, not upon `ConnectionManager.AfterTransaction` call.

File: src/NHibernate/Transaction/AdoTransaction.cs [hunk 2]
```diff
@@ -370,6 +370,7 @@ protected virtual void Dispose(bool isDisposing)
 					// don't dispose of multiple times.
 					return;
 				}
+				_isAlreadyDisposed = true;
```
Comment (fredericDelaporte) [inline src/NHibernate/Transaction/AdoTransaction.cs]: Change kept from #2144: flagging it at the end of this method instead of as soon as possible cause the method to be vulnerable to an endless loop, in case a `Dispose` is performed inside `AfterTransaction`, called later by this method.

This change was required by #2144 since it was calling `Dispose` in `AfterTransaction`. This PR here does not do it and so does not actually need that change, but still it is safer to have it.

File: src/NHibernate.Test/Ado/BatcherFixture.cs [hunk 3]
```diff
@@ -44,11 +43,11 @@ public void OneRoundTripInserts()
 		private void Cleanup()
 		{
 			using (ISession s = Sfi.OpenSession())
-			using (s.BeginTransaction())
+			using (var t = s.BeginTransaction())
 			{
 				s.CreateQuery("delete from VerySimple").ExecuteUpdate();
 				s.CreateQuery("delete from AlmostSimple").ExecuteUpdate();
-				s.Transaction.Commit();
+				t.Commit();
```
[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: I think it's better to isolate such changes in tests in separate commit to simplify review (at least in PR).
And you should add some Obsolete test that still uses `s.Transaction.Commit();` to make sure this case still works.

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: That would mean a commit that does not even compile, since we treat warnings as errors. It is troublesome.

[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: Just mark test as `[Obsolete]` and it should be OK

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: What? These tests are not obsolete, they need to be updated. We have to keep them, not drop them at next major release.

[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: You:
> That would mean a commit that does not even compile, since we treat warnings as errors. It is troublesome.

Me:
> Just mark test as [Obsolete] and it should be OK

And you've just committed tests marked as `[Obsolete]` for legacy `s.Transaction`... That's all I meant.. So not sure what's you `What?` about..

File: src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 1 above)
Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: This use case got me thinking if it's useful option for someone. If I get it right in old implementation you can supply some after transaction events before actual DB transaction is created.

File: src/NHibernate.Test/Ado/BatcherFixture.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: Misunderstanding all the way long:
The following:

> That would mean a commit that does not even compile, since we treat warnings as errors. It is troublesome.

Was refeting to:

> I think it's better to isolate such changes in tests in separate commit to simplify review (at least in PR).

So when you replied:

> Just mark new test as `[Obsolete]` and it should be OK

I thought you were willing me to flag as obsolete all the changed tests to avoid altering them an "ease" the review. Thus my reaction.

So the trouble remain: how do you want to split in separated commits the fix of the trouble and the fix of the tests, without issuing a commit that cannot compile?

File: src/NHibernate.Test/TransactionTest/TransactionFixture.cs [hunk 4]
```diff
@@ -230,5 +230,97 @@ public void WhenCommittingItemsWillAddThemTo2ndLevelCache()
...
+		{
+			int id;
+			using (var s = OpenSession())
+			using (s.BeginTransaction())
+			{
+				var person = new Person();
+				s.Save(person);
+				id = person.Id;
+
+				s.CurrentTransaction.Commit();
```
[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/TransactionTest/TransactionFixture.cs]: why not

File: src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 1 above)
Comment (fredericDelaporte) [reply src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: This sounds as quite a corner case.
You mainly could provide "after transaction" events that would have been happily dropped without ever being executed on next non-transacted statement run against the session...
Anyway, the property being just obsoleted, and kept with all its (anti) features, there are no breaking changes here.
Those adapting to use the new property we will have to adapt for starting the transaction first. I do not think there is any actual need for setting after transaction events before starting the transaction, simply because if you want to do anything out of the transaction on the session after setting them, you will lose them.

File: src/NHibernate.Test/Ado/BatcherFixture.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: I don't understand why non-compilable commit is an issue here. When you push multiple commits at once - only last one will be compiled.

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: Just a principle I think should be followedto (and I do not think I am alone): do not commit something that does not compile.
A separated commit should always compile. It can be cherry-picked, we can branch from it, ... It is not really "nice" to leave a commit which does not compile, even in a tree just meant for PR review.

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Ado/BatcherFixture.cs]: Done

File: src/NHibernate.Test/TransactionTest/TransactionFixture.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/TransactionTest/TransactionFixture.cs]: And done

File: src/NHibernate/ISession.cs [hunk 5]
```diff
@@ -764,6 +764,11 @@ public partial interface ISession : IDisposable
 		/// </summary>
 		ITransaction Transaction { get; }
 
+		/// <summary>
+		/// The current transaction if any, else <see langword="null" />.
+		/// </summary>
+		ITransaction CurrentTransaction { get; }
```
Comment (bahusoid) [inline src/NHibernate/ISession.cs]: With 2 commits breaking changes are spotted quite easily :) Do we really need it?

File: src/NHibernate/Async/Context/ThreadLocalSessionContext.cs [hunk 6]
```diff
@@ -32,18 +32,19 @@ private static async Task CleanupAnyOrphanedSessionAsync(ISessionFactory factory
 
 				try
 				{
-					if (orphan.Transaction != null && orphan.Transaction.IsActive)
+					try
 					{
-						try
+						var rollbackTask = orphan.CurrentTransaction?.RollbackAsync(cancellationToken);
```
Comment (bahusoid) [inline src/NHibernate/Async/Context/ThreadLocalSessionContext.cs]: Are you sure `IsActive` check is no more needed here?

File: src/NHibernate/ISession.cs (hunk 5 above)
Comment (fredericDelaporte) [reply src/NHibernate/ISession.cs]: Indeed I forgot, have to add it as an extension method, ...

We need it for obsoleting `ISession.Transaction`, unless we consider the return value from `BeginTransaction` is enough and that is the user concern to pass around the transaction if he needs it / needs to check if a transaction is ongoing.
Otherwise we could keep that `Transaction` property non-obsoleted, and just do a breaking change at 6.0. But it is not developer friendly to do breaking changes without warning in previous versions allowing to anticipate them.

File: src/NHibernate/Async/Context/ThreadLocalSessionContext.cs (hunk 6 above)
Comment (fredericDelaporte) [reply src/NHibernate/Async/Context/ThreadLocalSessionContext.cs]: It was previously needed because the `Transaction` was anyway never null, and was an inactive one if no transaction was ongoing.
Due to the `Transaction` property being not yet removed, it can still be created without being started altogether, so in fact the `IsActive` check should remain for now.

Comment (bahusoid) [reply src/NHibernate/Async/Context/ThreadLocalSessionContext.cs]: > It was previously needed because the Transaction was anyway never null, and was an inactive one if no transaction was ongoing.

`ITransaction.IsActive` might contain some custom logic for determination. That's my main concern here.. To me it seems `IsActive` check should remain even after  `Transaction` removal.

Comment (fredericDelaporte) [reply src/NHibernate/Async/Context/ThreadLocalSessionContext.cs]: It seems highly unlikely to me that such an implementation would be supported by NHibernate. It is not expected that a transaction might go inactive without an explicit commit or rollback call and without still supporting such a call if it goes inactive "by itslef". Most code just rollback or commit transactions it has explicitly started without checking that flag.

Comment (fredericDelaporte) [reply src/NHibernate/Async/Context/ThreadLocalSessionContext.cs]: But anyway, we can leave that for further reconsideration when `Transaction` properties would be actually removed.

File: src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs [hunk 7]
```diff
@@ -68,9 +68,9 @@ protected virtual async Task DropTemporaryTableIfNecessaryAsync(IQueryable persi
 			{
 				IIsolatedWork work = new TmpIdTableDropIsolatedWork(persister, log, session);
 
-				if (ShouldIsolateTemporaryTableDDL())
+				if (ShouldIsolateTemporaryTableDDL() && session.ConnectionManager.CurrentTransaction != null)
 				{
-					session.ConnectionManager.Transaction.RegisterSynchronization(
+					session.ConnectionManager.CurrentTransaction.RegisterSynchronization(
```
Comment (bahusoid) [inline src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: If you think that's it's worth adding `CurrentTransaction` to interface than we should use it instead  everywhere to make sure implementation is not ovveriden.

File: src/NHibernate/ISession.cs [hunk 8]
```diff
@@ -763,14 +771,9 @@ public partial interface ISession : IDisposable
 		/// Get the current Unit of Work and return the associated <c>ITransaction</c> object.
 		/// </summary>
 		// Since v5.3
-		[Obsolete("Use CurrentTransaction instead, and check for nulls.")]
+		[Obsolete("Use GetCurrentTransaction extension method instead, and check for nulls.")]
```
Comment (bahusoid) [inline src/NHibernate/ISession.cs]: Why `nulls`. Shouldn't it be simply `null`? Typo?

File: src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs [hunk 9]
```diff
@@ -96,41 +95,32 @@ public async Task WasCommittedOrRolledBackAsync()
...
+					Assert.IsFalse(s.GetCurrentTransaction().WasRolledBack);
 					await (t.CommitAsync());
 
-					// ISession.Transaction returns a new transaction
-					// if the previous one completed!
-					Assert.IsNotNull(s.Transaction);
-					Assert.IsFalse(t == s.Transaction);
+					// ISession.GetCurrentTransaction() does not return a new transaction
+					// if the previous one is completed.
+					Assert.IsNull(s.GetCurrentTransaction());
```
[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs]: Yes, `Transaction` property's backing field is set to `null` in `ConnectionManager.AfterTransaction`. So if you read it after commit/rollback, you have a new instance, not `begun`, not committed or rollbacked.
I think people using the property are used to that, and that the xml comment `Get the current transaction if any, else <see langword="null" />` will be enough for them to understand they will get null after commit or rollback.
The properties `WasCommitted` / `Rollacked` serve for those who keep their own reference to the transaction object (and serve likely in after transaction events too).

File: src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 7 above)
Comment (fredericDelaporte) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: Previous `Transaction` property implementation was not either (not `virtual`). So only a custom `ISession` may benefit of this change. (And of course only after we have put `CurrentTransaction` into the interface.)

Comment (fredericDelaporte) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: I am not committing your suggestion as it needs more changes to be effective. I will add another commit.

File: src/NHibernate/ISession.cs (hunk 8 above)
Comment (fredericDelaporte) [reply src/NHibernate/ISession.cs]: Just a kind of contraction of `null values`, not really good language anyway. Will adjust.

File: src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 7 above)
Comment (fredericDelaporte) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: In fact this change is invalid.
`session` is not an `ISession`, but an `ISessionImplementor`. It has never had a transaction property, and so the old code was just right going through the connection manager.

File: src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs]: > I think people using the property are used to that

What about people who didn't use this property before. Note should be added for them.

Actually your new comment is not helpful. Previous one explains strange unexpected behavior - we still in transaction scope but `s.Transaction` is already assigned to new instance. And after refactoring comment simply makes no sense  - why would anyone expect here new transaction. It's null that should be explained here.
So it should be something like:
`// ISession.GetCurrentTransaction() returns null if previous transaction is completed!`

File: src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 7 above)
Comment (bahusoid) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: > So only a custom ISession may benefit of this change. (And of course only after we have put CurrentTransaction into the interface.)

I don't get this point. If we add this to interface we can expect custom implementations. No?
So does it make sense to add `GetCurrentTransaction` to interface if it may results in different behavior - and here custom logic won't be used. Maybe it's enough to have it as extension methods?

> I am not committing your suggestion as it needs

I'm using suggested change just for illustration. I don''t expect it to be committed.

Comment (fredericDelaporte) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: We cannot do what you ask anyway. It was not supported by the previous `Transaction` property because it does not exist on the type this `session` variable is. And the change you are asking here is unrelated to what this PR aims to fix.

Comment (bahusoid) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: My main point here -  it seems `ISession/IStatelessSession` is a wrong place for `Transaction/CurrentTransaction` property. It seems we should keep it simply as extension, so if you agree just remove TODO about adding new method to interface. And if someone needs extensibility - `CurrentTransaction` should be added directly to `ISessionImplementor` (with different PR)

P.S. This PR still contains breaking changes in `IStatelessSession`.

File: src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs]: > What about people who didn't use this property before. Note should be added for them.

This:

> the xml comment `Get the current transaction if any, else <see langword="null" />`

Should also tell them. Anyway I am rewording it to make it more explicit.

[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs]: > `Get the current transaction if any, else <see langword="null" />`

I would change it to something like:
`Get active current tranasaction if any, else <see langword="null">. Please note it returns null if current transaction is completed (commited or rolledback)`

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs]: I have put:

> Get the current transaction if any is ongoing, else <see langword="null" />.

Clear enough I think, and concise.

File: src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs (hunk 7 above)
Comment (fredericDelaporte) [reply src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs]: Fixed, previous commits squashed, new changes are in the fixup commit.
Some glitches in previous fixup commits have been adjusted while squashing.

**Comment by fredericDelaporte** [comment]
Rebased and fixup squashed.

**Comment by fredericDelaporte** [comment]
Rebased for checking the generator update was not requiring a regen for this PR.

**Comment by hazzik** [comment]
I did a merge as 2 commits have better representation of the work done.
