### PR TITLE
Apply filters for entity joins in hql

### LINKED ISSUE #2549: ApplyFilter does not work on join statements in LINQ
Hi 
We upgraded NH from 5.2.7 to 5.3.3.
After upgrade we had an issue that ApplyFilter  does not work with joins.
Same join statement working fine with version 5.2.7.

You can find testcase implementation below link.
https://github.com/esabah/NHibernateBugTest/blob/master/NHibernateBugTest/TxnDefTest.cs

TxnDefMember entity has a custom filter which applies filter on mbrId field.

`         ApplyFilter<MemberConditionFilter>();`

But mbrId  not included in sql query in 5.3.3 version.
`(from txndef in session.Query<TxnDef>()
join txnDefMember in session.Query<TxnDefMember>() on txndef.Guid equals txnDefMember.Id.TxnDefGuid
select txnDefMember.BucketName)`

same query returns 8 records in 5.3.3
and returns 4 records in 5.2.7

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #2549

Just make `JoinSequence` apply standard logic that takes care of everything

### CODE REVIEW

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs [hunk 1]
```diff
@@ -8,44 +7,9 @@ namespace NHibernate.Hql.Ast.ANTLR.Tree
 {
 	class EntityJoinJoinSequenceImpl : JoinSequence
 	{
-		private readonly EntityType _entityType;
-		private readonly string _tableName;
-		private readonly string _tableAlias;
-		private readonly JoinType _joinType;
-
-		public EntityJoinJoinSequenceImpl(ISessionFactoryImplementor factory, EntityType entityType, string tableName, string tableAlias, JoinType joinType):base(factory)
+		public EntityJoinJoinSequenceImpl(ISessionFactoryImplementor factory, EntityType entityType, string tableAlias, JoinType joinType):base(factory)
```
Comment (hazzik) [inline src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs:10]: nit: Please put `: base(factory)` on a new line, or, at least, add spaces around `:`.

**Comment by hazzik** [comment]
Is it a backport of some changes from `master`?

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs [hunk 2]
```diff
@@ -8,44 +7,9 @@ namespace NHibernate.Hql.Ast.ANTLR.Tree
 {
 	class EntityJoinJoinSequenceImpl : JoinSequence
```
Comment (hazzik) [inline src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs:8]: Let's just kill this class.

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs [hunk 3]
```diff
@@ -15,12 +17,10 @@ public EntityJoinFromElement(FromClause fromClause, IQueryable entityPersister,
 			EntityType entityType = (EntityType) entityPersister.Type;
 			InitializeEntity(fromClause, entityPersister.EntityName, entityPersister, entityType, alias, tableAlias);
 
-			JoinSequence = new EntityJoinJoinSequenceImpl(
-				SessionFactoryHelper.Factory,
-				entityType,
-				entityPersister.TableName,
-				tableAlias,
-				joinType);
+			//Note: filters don't work with entity joins
```
Comment (hazzik) [inline src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs:20]: This comment is copied from `master`, where `EntityJoinJoinSequenceImpl` already become the same as here. Not sure if this comment is relevant or not.

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs (hunk 2 above)
Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs]: I thought to keep it just for reference with hibernate implementation. 

>Is it a backport of some changes from master

Yes it's been simplified with table group joins implementation https://github.com/nhibernate/nhibernate-core/pull/2361

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs (hunk 3 above)
Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs:20]: No it's not valid on master. It's been valid only for initial implementation and I just copy/pasted it. So it should go away with merge one way or another

Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs:20]: > filters don't work with entity joins

It's not valid because this PR is about working filters for entity joins  :)

Comment (hazzik) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs]: Ok, I've deleted comment.

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs (hunk 2 above)
Comment (hazzik) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs]: > Yes it's been simplified with table group joins implementation

I don't get it. In 5.3.x we don't have table group joins, but the filters still work?

 > I thought to keep it just for reference with hibernate implementation.

Ok. Let's don't keep it.

**Review by hazzik — APPROVED** [review]

File: src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs (hunk 2 above)
Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs]: > In 5.3.x we don't have table group joins, but the filters still work?

Yep. Whatever is supported for many-to-one is now supported for entity join. We just removed custom entity join processing

Comment (bahusoid) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs]: >Ok. Let's don't keep it.

Ok But let's at least have comment about it.

**Review by hazzik — APPROVED** [review]

**Comment by bahusoid** [comment]
When merging to master in case of conflicts (due to https://github.com/nhibernate/nhibernate-core/pull/2361) - just take changes from 5.3.x branch.
