### PR TITLE
Fix missing ConfigureAwait(false) in FutureEnumerable

### LINKED ISSUE #2677: FutureEnumerable - GetEnumerableAsync - missing configureawait
Ehhhh, synchronization contexts... missing configureawait(false) in https://github.com/nhibernate/nhibernate-core/blob/d6e054f2bbfda43fccf82d54b7cda4e5aecbab5d/src/NHibernate/Multi/QueryBatchExtensions.cs#L581

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #2677 

This one can also be considered for backporting to 5.2

### CODE REVIEW

File: src/NHibernate/Async/Multi/QueryBatchExtensions.cs [hunk 1]
```diff
@@ -61,6 +61,16 @@ public async Task<IList<TResult>> GetValueAsync(CancellationToken cancellationTo
 			}
 		}
 
+		partial class FutureEnumerable<TResult> : IFutureEnumerable<TResult>
```
Comment (hazzik) [inline src/NHibernate/Async/Multi/QueryBatchExtensions.cs:64]: Is this auto-generated?

**Review by hazzik — APPROVED** [review]

File: src/NHibernate/Async/Multi/QueryBatchExtensions.cs (hunk 1 above)
Comment (hazzik) [reply src/NHibernate/Async/Multi/QueryBatchExtensions.cs:64]: Yes.
