### PR TITLE
Fix parameter detection for Contains method for Linq provider

### LINKED ISSUE #2512: Linq queries with a condition after a projection on a collection fail
I've just updated from NHibernate 5.2.7 to 5.3.2 and now a few of my tests are failing. Although I get a few different exceptions, some of them seem to be related because they all only happen if a Linq query contains a specific condition after a projection on a collection (`.SelectMany(x => x.Collection)`).

Sample code:

    Person singlePersonParameter = ...
    Person[] personArrayParameter = new[] { singlePersonParameter };
    long[] personIdsArrayParameter = personArrayParameter.Select(p => p.Id).ToArray();

    // Works
    result = Query<Person>()
       .Where(x => x == singlePersonParameter)
       .ToArray();
    
    // Works
    result = Query<Customer>()
       .SelectMany(x => x.Persons)
       .Where(x => x.Id == singlePersonParameter.Id)
       .ToArray();
    
    // Fails with exception in NHibernate code (1)
    result = Query<Customer>()
       .SelectMany(x => x.Persons)
       .Where(x => x == singlePersonParameter)
       .ToArray();
    
    // Works
    result = Query<Person>()
       .Where(x => personArrayParameter.Contains(x))
       .ToArray();
    
    // Works
    result = Query<Customer>()
       .SelectMany(x => x.Persons)
       .Where(x => personIdsArrayParameter.Contains(x.Id))
       .ToArray();
    
    // Fails with exception in NHibernate code (2)
    result = Query<Customer>()
       .SelectMany(x => x.Persons)
       .Where(x => personArrayParameter.Contains(x))
       .ToArray();

The exception (1) is

    NHibernate.TypeMismatchException: 'left and right hand sides of a binary logic operator were incompatibile [My.Namespace.Person : System.Collections.Generic.ISet`1[[My.Namespace.Person, MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](My.Namespace.Customer.Persons)]'

and the full stack is

    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.Tree.BinaryLogicOperatorNode.MutateRowValueConstructorSyntaxesIfNecessary(NHibernate.Type.IType lhsType, NHibernate.Type.IType rhsType) Line 95
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.Tree.BinaryLogicOperatorNode.Initialize() Line 79
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.PrepareLogicOperator(NHibernate.Hql.Ast.ANTLR.Tree.IASTNode operatorNode) Line 956
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.comparisonExpr() Line 7831
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.logicalExpr() Line 6575
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.whereClause() Line 6250
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.unionedQuery() Line 1819
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.query() Line 1583
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.selectStatement() Line 432
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.statement() Line 310
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate() Line 613
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(string collectionRole) Line 459
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.DoCompile(System.Collections.Generic.IDictionary<string, string> replacements, bool shallow, string collectionRole) Line 361
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(NHibernate.IQueryExpression queryExpression, NHibernate.Hql.Ast.ANTLR.Tree.IASTNode ast, string queryIdentifier, string collectionRole, bool shallow, System.Collections.Generic.IDictionary<string, NHibernate.IFilter> filters, NHibernate.Engine.ISessionFactoryImplementor factory) Line 43
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(NHibernate.IQueryExpression queryExpression, string collectionRole, bool shallow, System.Collections.Generic.IDictionary<string, NHibernate.IFilter> filters, NHibernate.Engine.ISessionFactoryImplementor factory) Line 20
    NHibernate.dll!NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(NHibernate.IQueryExpression queryExpression, bool shallow, System.Collections.Generic.IDictionary<string, NHibernate.IFilter> enabledFilters) Line 63
    NHibernate.dll!NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(NHibernate.IQueryExpression queryExpression, bool shallow) Line 584
    NHibernate.dll!NHibernate.Impl.AbstractSessionImpl.CreateQuery(NHibernate.IQueryExpression queryExpression) Line 552
    NHibernate.dll!NHibernate.Linq.DefaultQueryProvider.PrepareQuery(System.Linq.Expressions.Expression expression, out NHibernate.IQuery query) Line 208
    NHibernate.dll!NHibernate.Linq.DefaultQueryProvider.ExecuteList<My.Namespace.Person>(System.Linq.Expressions.Expression expression) Line 107
    NHibernate.dll!NHibernate.Linq.NhQueryable<My.Namespace.Person>.System.Collections.Generic.IEnumerable<My.Namespace.Person>.GetEnumerator() Line 65
    System.Core.dll!System.Linq.Buffer<My.Namespace.Person>.Buffer(System.Collections.Generic.IEnumerable<My.Namespace.Person> source)
    System.Core.dll!System.Linq.Enumerable.ToArray<My.Namespace.Person>(System.Collections.Generic.IEnumerable<My.Namespace.Person> source)

The exception (2) is `System.InvalidOperationException: Sequence contains no elements.` and the full stack is

    System.Core.dll!System.Linq.Enumerable.First<string>(System.Collections.Generic.IEnumerable<string> source)
    NHibernate.dll!NHibernate.SqlCommand.SqlCommandImpl.ResetParametersIndexesForTheCommand(int singleSqlParametersOffset) Line 111
    NHibernate.dll!NHibernate.Loader.Loader.PrepareQueryCommand(NHibernate.Engine.QueryParameters queryParameters, bool scroll, NHibernate.Engine.ISessionImplementor session) Line 1441
    NHibernate.dll!NHibernate.Loader.Loader.DoQuery(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters, bool returnProxies, NHibernate.Transform.IResultTransformer forcedResultTransformer, NHibernate.Cache.QueryCacheResultBuilder queryCacheResultBuilder) Line 503
    NHibernate.dll!NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters, bool returnProxies, NHibernate.Transform.IResultTransformer forcedResultTransformer, NHibernate.Cache.QueryCacheResultBuilder queryCacheResultBuilder) Line 303
    NHibernate.dll!NHibernate.Loader.Loader.DoList(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters, NHibernate.Transform.IResultTransformer forcedResultTransformer, NHibernate.Cache.QueryCacheResultBuilder queryCacheResultBuilder) Line 1972
    NHibernate.dll!NHibernate.Loader.Loader.ListIgnoreQueryCache(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters) Line 1837
    NHibernate.dll!NHibernate.Loader.Loader.List(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters, System.Collections.Generic.ISet<string> querySpaces) Line 1825
    NHibernate.dll!NHibernate.Loader.Hql.QueryLoader.List(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters) Line 325
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(NHibernate.Engine.ISessionImplementor session, NHibernate.Engine.QueryParameters queryParameters) Line 119
    NHibernate.dll!NHibernate.Engine.Query.HQLQueryPlan.PerformList(NHibernate.Engine.QueryParameters queryParameters, NHibernate.Engine.ISessionImplementor session, System.Collections.IList results) Line 151
    NHibernate.dll!NHibernate.Impl.SessionImpl.List(NHibernate.IQueryExpression queryExpression, NHibernate.Engine.QueryParameters queryParameters, System.Collections.IList results, object filterConnection) Line 554
    NHibernate.dll!NHibernate.Impl.SessionImpl.List(NHibernate.IQueryExpression queryExpression, NHibernate.Engine.QueryParameters queryParameters, System.Collections.IList results) Line 524
    NHibernate.dll!NHibernate.Impl.AbstractSessionImpl.List<My.Namespace.Person>(NHibernate.IQueryExpression query, NHibernate.Engine.QueryParameters parameters) Line 183
    NHibernate.dll!NHibernate.Impl.AbstractQueryImpl2.List<My.Namespace.Person>() Line 108
    NHibernate.dll!NHibernate.Linq.DefaultQueryProvider.ExecuteList<My.Namespace.Person>(System.Linq.Expressions.Expression expression) Line 114
    NHibernate.dll!NHibernate.Linq.NhQueryable<My.Namespace.Person>.System.Collections.Generic.IEnumerable<My.Namespace.Person>.GetEnumerator() Line 65
    System.Core.dll!System.Linq.Buffer<My.Namespace.Person>.Buffer(System.Collections.Generic.IEnumerable<My.Namespace.Person> source)
    System.Core.dll!System.Linq.Enumerable.ToArray<My.Namespace.Person>(System.Collections.Generic.IEnumerable<My.Namespace.Person> source)

### LINKED ISSUE #2514: Entity with field interceptor are not correctly passed as Linq parameters
I've just updated from NHibernate 5.2.7 to 5.3.2 and now a few of my tests are failing. Some of them all have the same error where Oracle reports inconsistent datatypes for a parameter.

It looks like the affected Linq queries all pass the entities directly as a parameter, so NHibernate is responsible for extracting the Id from the object. This doesn't work any more in 5.3.x when the entity parameter type is `XyzProxyForFieldInterceptor` (which I think is the case if an entity with a lazy property or lazy component is loaded).

Example query:

    // Person is mapped with a lazy component
    Person personParameter = session.Get<Person>(123);
    
    // Fails with Oracle error "inconsistent datatypes"
    var result = Query<Customer>()
       .Where(x => x.Persons.Contains(personParameter))
       .ToArray();

The exception message contains the information `Name:p1 - Value:{PersonProxyForFieldInterceptor}`.
The SQL log output confirms the wrong parameter by showing something like this: `:p0 = 0x0001000000FF... [Type: Object (0:0:0)]`

If I change the query so that a just persisted object is used as a parameter (which isn't of type `PersonProxyForFieldInterceptor` but instead just of type `Person`) the query works correctly.

### LINKED ISSUE #2515: InvalidCastException for Linq query with subquery
I've just updated from NHibernate 5.2.7 to 5.3.2 and now one of my queries is failing.

I've simplified the failing query to this:

    Customer customerParameter = ...

    var customersSubquery = Query<SomeEntity>()
       .Select(x => x.Customer)
       .Where(x => x != customerParameter);
    
    var result = Query<SomeOtherEntity>()
       .Where(x => customersSubquery.Contains(x.Customer))
       .ToArray();

This is the exception I get:

    System.InvalidCastException: Unable to cast object of type 'NHibernate.Persister.Entity.SingleTableEntityPersister' to type 'NHibernate.Persister.Collection.IQueryableCollection'.

Full stack:

    NHibernate.dll!NHibernate.Linq.Visitors.ParameterTypeLocator.SetParameterTypes(System.Collections.Generic.IDictionary<System.Linq.Expressions.ConstantExpression, NHibernate.Param.NamedParameter> parameters, Remotion.Linq.QueryModel queryModel, System.Type targetType, NHibernate.Engine.ISessionFactoryImplementor sessionFactory, bool removeMappedAsCalls) Line 116
    NHibernate.dll!NHibernate.Linq.NhLinqExpression.Translate(NHibernate.Engine.ISessionFactoryImplementor sessionFactory, bool filter) Line 94
    NHibernate.dll!NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(NHibernate.IQueryExpression queryExpression, string collectionRole, bool shallow, System.Collections.Generic.IDictionary<string, NHibernate.IFilter> filters, NHibernate.Engine.ISessionFactoryImplementor factory) Line 20
    NHibernate.dll!NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(NHibernate.IQueryExpression queryExpression, bool shallow, System.Collections.Generic.IDictionary<string, NHibernate.IFilter> enabledFilters) Line 63
    NHibernate.dll!NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(NHibernate.IQueryExpression queryExpression, bool shallow) Line 584
    NHibernate.dll!NHibernate.Impl.AbstractSessionImpl.CreateQuery(NHibernate.IQueryExpression queryExpression) Line 552
    NHibernate.dll!NHibernate.Linq.DefaultQueryProvider.PrepareQuery(System.Linq.Expressions.Expression expression, out NHibernate.IQuery query) Line 208
    NHibernate.dll!NHibernate.Linq.DefaultQueryProvider.ExecuteList<MyEntityType>(System.Linq.Expressions.Expression expression) Line 107
    NHibernate.dll!NHibernate.Linq.NhQueryable<MyEntityType>.System.Collections.Generic.IEnumerable<MyEntityType>.GetEnumerator() Line 65
    System.Core.dll!System.Linq.Buffer<MyEntityType>.Buffer(System.Collections.Generic.IEnumerable<MyEntityType> source)
    System.Core.dll!System.Linq.Enumerable.ToArray<MyEntityType>(System.Collections.Generic.IEnumerable<MyEntityType> source)

### PR DESCRIPTION
**Pull request by maca88**
Fix for a regression made by #2365.

Fixes #2515
Fixes #2514
Fixes #2512

### CODE REVIEW

**Comment by maca88** [comment]
Rebased.

File: src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs [hunk 1]
```diff
@@ -282,41 +281,53 @@ protected override Expression VisitConstant(ConstantExpression node)
...
-						{
-							AddRelatedExpression(constantExpression, nestedMemberExpression);
-						}
-					}
+					return false;
+				}
+
+				var left = UnwrapUnary(mainFromClause.FromExpression);
+				var right = UnwrapUnary(containsOperator.Item);
+				if (left.NodeType == ExpressionType.Constant)
```
Comment (bahusoid) [inline src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs:308]: Why explicit branches with similar code? Can't all it be handled at once? Something like:
```C#
var left = UnwrapUnary(Visit(mainFromClause.FromExpression));
var right = UnwrapUnary(Visit(containsOperator.Item));
// The constant is on the left side (e.g. db.Users.Where(o => users.Contains(o)))
// The constant is on the right side (e.g. db.Customers.Where(o => o.Orders.Contains(item)))
if (left.NodeType != ExpressionType.Constant && right.NodeType != ExpressionType.Constant)
{
	return false;
}
```

Comment (maca88) [reply src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs]: Yes it can be handled at once, applied you suggestion.

**Review by hazzik — APPROVED** [review]

**Review by bahusoid — APPROVED** [review]
