### PR TITLE
Fix fetching many-to-many with subclasses

### LINKED ISSUE #3239: Incorrect SQL genererated after upgrading NH 5.3.15 -> NH 5.4.0
Hi,

I've been using NHibernate for many years and I like it very much, thank you everybody who is contributing!

When I upgraded from NHibernate.5.3.15 with net461 to NHibernate.5.4.0 with net48 two of my hundreds of mapped 
entities (Property and BeWriter) could not be loaded anymore. The error was 

NHibernate.Exceptions.GenericADOException : could not execute query
System.Data.SqlClient.SqlException : Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.

The reason was that the sql query was incorrect. As you can see below the parentheses are incorrect and also
the alias sets2_1_ is not defined, it should have been sets2_.

For entity Property it looked like this:

=== SQL query ===
SELECT
        TOP (@p0) this_.id      AS id1_91_2_         ,
        this_.[type]            AS type2_91_2_       ,
        this_.[name]            AS name3_91_2_       ,
        this_.[data_type]       AS data4_91_2_       ,
        this_.[is_vector]       AS is5_91_2_         ,
        this_.[value_table]     AS value6_91_2_      ,
        sets2_.property_id      AS property2_55_4_   ,
        set3_.id                AS set1_55_4_        ,
        set3_.id                AS id1_53_0_         ,
        set3_.[set_type]        AS set2_53_0_        ,
        set3_.[name]            AS name3_53_0_       ,
        set3_.[description]     AS description4_53_0_,
        set3_.parent_set_id     AS parent5_53_0_     ,
        set3_1_.property_id     AS property2_182_0_  ,
        set3_1_.filtered_set_id AS filtered3_182_0_  ,
        set3_1_.[inclusive]     AS inclusive4_182_0_ ,
        set3_1_.[string_val]    AS string5_182_0_    ,
        set3_1_.[float_val]     AS float6_182_0_     ,
        set3_1_.[date_val]      AS date7_182_0_      ,
        set3_2_.source_id       AS source2_183_0_    ,
        source4_.id             AS id1_90_1_         ,
        source4_.[name]         AS name2_90_1_       ,
        source4_.[description]  AS description3_90_1_
FROM
        ahs2_property this_
LEFT OUTER JOIN
        (ahs2_property_set sets2_)
ON
        this_.id=sets2_1_.property_id
LEFT OUTER JOIN
        ahs2_set set3_
ON
        sets2_.set_id=set3_.id
LEFT OUTER JOIN
        ahs2_filter_set set3_1_
ON
        set3_.id=set3_1_.set_id
LEFT OUTER JOIN
        ahs2_source_series_type set3_2_
ON
        set3_.id=set3_2_.set_id
LEFT OUTER JOIN
        ahs2_source source4_
ON
        set3_2_.source_id=source4_.id
		
=== Database and Dialect ===

Database and dialect: I've tried 
1. NHibernate.Dialect.MsSql2012Dialect with a database on a Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
2. NHibernate.Dialect.MsSql2012Dialect with a database on a Microsoft SQL Server 2016 (SP2-GDR) (KB4583460)
3. NHibernate.Dialect.MsSql2008Dialect with a database on a Microsoft SQL Server 2008 (SP3) - 10.0.5538.0 (X64) 

All with the same result.

=== The code I'm running ===

/// <summary>
        /// Test all entity mappings by loading them one by one
        /// </summary>
        [Test, TestCaseSource("ClassMetaData")]
        public void EntityTest(KeyValuePair<string, IClassMetadata> entry)
        {
            using(var session = NHUtils.SessionFactory.OpenSession()) {
                var meta = entry.Value;
                var query = session.CreateCriteria(entry.Key);

                for(var i = 0; i < meta.PropertyNames.Length; ++i) {
                    if(meta.PropertyTypes[i].IsAssociationType) {
                        query.Fetch(SelectMode.Fetch, meta.PropertyNames[i]);
                    }
                }

                // If this row throws there's a mismatch between the database and the hibernate mappings
                query.SetMaxResults(1).List();
            }
        }
		
=== The mapping ===

I'm using Fluent NHibernate and the resulting mapping looks like this:

<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" auto-import="false" namespace="Admc.Data.Ahs" assembly="Admc.Data, Version=3.5.9.0, Culture=neutral, PublicKeyToken=null" xmlns="urn:nhibernate-mapping-2.2">
  <class name="Property" table="ahs2_property" dynamic-update="true" dynamic-insert="true">
    <id name="Id" column="id" type="Int32">
      <generator class="native" />
    </id>
    <property name="Type" type="Admc.Data.EnumMapper`1[[Admc.Data.Ahs.PropertyType, Admc.Data, Version=3.5.9.0, Culture=neutral, PublicKeyToken=null]], Admc.Data, Version=3.5.9.0, Culture=neutral, PublicKeyToken=null" column="`type`" not-null="true" />
    <property name="Name" type="AnsiString" column="`name`" length="50" not-null="true" />
    <property name="DataType" type="Admc.Data.EnumMapper`1[[Admc.Data.DataType, Admc.Data, Version=3.5.9.0, Culture=neutral, PublicKeyToken=null]], Admc.Data, Version=3.5.9.0, Culture=neutral, PublicKeyToken=null" column="`data_type`" not-null="true" />
    <property name="IsVector" column="`is_vector`" not-null="true" />
    <property name="ValueTable" type="AnsiString" column="`value_table`" length="50" />
    <set name="Sets" table="ahs2_property_set" cascade="save-update, persist">
      <key column="property_id" />
      <many-to-many class="Set" column="set_id" />
    </set>
  </class>
</hibernate-mapping>

=== Database schema ===
The database schema is the following:

-- data_type --

CREATE TABLE [dbo].[ahs2_data_type] (
    [name] VARCHAR (50) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT PK_ahs2_data_type PRIMARY KEY
);

-- property_type --

CREATE TABLE [dbo].[ahs2_property_type] (
    [name] VARCHAR (50) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT PK_ahs2_property_type PRIMARY KEY
);

-- set_type --

CREATE TABLE [dbo].[ahs2_set_type] (
    [name] VARCHAR (50) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT PK_ahs2_set_type PRIMARY KEY
);

-- property --

CREATE TABLE [dbo].[ahs2_property] (
    [id]          INT          IDENTITY (1, 1) NOT NULL CONSTRAINT PK_ahs2_property PRIMARY KEY,
    [type]        VARCHAR (50) COLLATE Latin1_General_BIN NOT NULL,
    [name]        VARCHAR (50) NOT NULL,
    [data_type]   VARCHAR (50) COLLATE Latin1_General_BIN NOT NULL,
    [value_table] VARCHAR (50) NULL,
    [is_vector]   BIT          NOT NULL DEFAULT 0,

    CONSTRAINT UK_ahs2_property_name_type UNIQUE([name], [type])
);

ALTER TABLE [dbo].[ahs2_property]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_property_ahs2_property_type] FOREIGN KEY([type])
REFERENCES [dbo].[ahs2_property_type] ([name])
GO

ALTER TABLE [dbo].[ahs2_property] CHECK CONSTRAINT [FK_ahs2_property_ahs2_property_type]
GO

ALTER TABLE [dbo].[ahs2_property]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_property_ahs2_data_type] FOREIGN KEY([data_type])
REFERENCES [dbo].[ahs2_data_type] ([name])
GO

ALTER TABLE [dbo].[ahs2_property] CHECK CONSTRAINT [FK_ahs2_property_ahs2_data_type]
GO

-- set --

CREATE TABLE [dbo].[ahs2_set] (
    [id]            INT           IDENTITY (1, 1) NOT NULL CONSTRAINT PK_ahs2_set PRIMARY KEY,
    [set_type]      VARCHAR (50)  COLLATE Latin1_General_BIN NOT NULL,
    [name]          VARCHAR (50)  NOT NULL,
    [parent_set_id] INT           NULL,
    [description]   VARCHAR (255) NULL,
    [unique_name]   BIT           NOT NULL CONSTRAINT DF_ahs2_set_unique_name DEFAULT (0)

);

ALTER TABLE [dbo].[ahs2_set]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_set_ahs2_set] FOREIGN KEY([parent_set_id])
REFERENCES [dbo].[ahs2_set] ([id])
GO

ALTER TABLE [dbo].[ahs2_set] CHECK CONSTRAINT [FK_ahs2_set_ahs2_set]
GO

ALTER TABLE [dbo].[ahs2_set]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_set_ahs2_set_type] FOREIGN KEY([set_type])
REFERENCES [dbo].[ahs2_set_type] ([name])
GO

ALTER TABLE [dbo].[ahs2_set] CHECK CONSTRAINT [FK_ahs2_set_ahs2_set_type]
GO

-- property_set --

CREATE TABLE [dbo].[ahs2_property_set] (
    [property_id] INT NOT NULL,
    [set_id]      INT NOT NULL,

    CONSTRAINT PK_ahs2_property_set PRIMARY KEY([set_id], [property_id])
);

ALTER TABLE [dbo].[ahs2_property_set]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_property_set_ahs2_property] FOREIGN KEY([property_id])
REFERENCES [dbo].[ahs2_property] ([id])
GO

ALTER TABLE [dbo].[ahs2_property_set] CHECK CONSTRAINT [FK_ahs2_property_set_ahs2_property]
GO

ALTER TABLE [dbo].[ahs2_property_set]  WITH CHECK ADD  CONSTRAINT [FK_ahs2_property_set_ahs2_set] FOREIGN KEY([set_id])
REFERENCES [dbo].[ahs2_set] ([id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ahs2_property_set] CHECK CONSTRAINT [FK_ahs2_property_set_ahs2_set]
GO

=== Experiments ===

I made a table ahs2_properti (that looked the same as ahs2_property) and a table ahs2_properti_set (which was the same 
as ahs2_property_set except it was referencing ahs2_properti instead of ahs2_property). And then I mapped an entity Properti
with the same code as entity Property, and the mapping xml-files was equivalent for Properti and Property. But for Properti 
everything worked fine. The properti-sql looked perfect.

Both Property and BeWriter contains a column type and I thought that might be the problem but I have several objects with type 
columns and there is no problem there. Also Properti had a type column without problems.

=== Error message ===

NHibernate.Exceptions.GenericADOException : could not execute query
[ SELECT this_.id as id1_91_2_, this_.[type] as type2_91_2_, this_.[name] as name3_91_2_, this_.[data_type] as data4_91_2_, this_.[is_vector] as is5_91_2_, this_.[value_table] as value6_91_2_, sets2_.property_id as property2_55_4_, set3_.id as set1_55_4_, set3_.id as id1_53_0_, set3_.[set_type] as set2_53_0_, set3_.[name] as name3_53_0_, set3_.[description] as description4_53_0_, set3_.parent_set_id as parent5_53_0_, set3_1_.property_id as property2_182_0_, set3_1_.filtered_set_id as filtered3_182_0_, set3_1_.[inclusive] as inclusive4_182_0_, set3_1_.[string_val] as string5_182_0_, set3_1_.[float_val] as float6_182_0_, set3_1_.[date_val] as date7_182_0_, set3_2_.source_id as source2_183_0_, source4_.id as id1_90_1_, source4_.[name] as name2_90_1_, source4_.[description] as description3_90_1_ FROM ahs2_property this_ left outer join  (ahs2_property_set sets2_) on this_.id=sets2_1_.property_id left outer join ahs2_set set3_ on sets2_.set_id=set3_.id left outer join ahs2_filter_set set3_1_ on set3_.id=set3_1_.set_id left outer join ahs2_source_series_type set3_2_ on set3_.id=set3_2_.set_id left outer join ahs2_source source4_ on set3_2_.source_id=source4_.id ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY ]
[SQL: SELECT this_.id as id1_91_2_, this_.[type] as type2_91_2_, this_.[name] as name3_91_2_, this_.[data_type] as data4_91_2_, this_.[is_vector] as is5_91_2_, this_.[value_table] as value6_91_2_, sets2_.property_id as property2_55_4_, set3_.id as set1_55_4_, set3_.id as id1_53_0_, set3_.[set_type] as set2_53_0_, set3_.[name] as name3_53_0_, set3_.[description] as description4_53_0_, set3_.parent_set_id as parent5_53_0_, set3_1_.property_id as property2_182_0_, set3_1_.filtered_set_id as filtered3_182_0_, set3_1_.[inclusive] as inclusive4_182_0_, set3_1_.[string_val] as string5_182_0_, set3_1_.[float_val] as float6_182_0_, set3_1_.[date_val] as date7_182_0_, set3_2_.source_id as source2_183_0_, source4_.id as id1_90_1_, source4_.[name] as name2_90_1_, source4_.[description] as description3_90_1_ FROM ahs2_property this_ left outer join  (ahs2_property_set sets2_) on this_.id=sets2_1_.property_id left outer join ahs2_set set3_ on sets2_.set_id=set3_.id left outer join ahs2_filter_set set3_1_ on set3_.id=set3_1_.set_id left outer join ahs2_source_series_type set3_2_ on set3_.id=set3_2_.set_id left outer join ahs2_source source4_ on set3_2_.source_id=source4_.id ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY]
  ----> System.Data.SqlClient.SqlException : Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
Data:
  HelpLink.ProdName: Microsoft SQL Server
  HelpLink.ProdVer: 15.00.2000
  HelpLink.EvtSrc: MSSQLServer
  HelpLink.EvtID: 102
  HelpLink.BaseHelpUrl: http://go.microsoft.com/fwlink
  HelpLink.LinkId: 20476
  actual-sql-query: SELECT this_.id as id1_91_2_, this_.[type] as type2_91_2_, this_.[name] as name3_91_2_, this_.[data_type] as data4_91_2_, this_.[is_vector] as is5_91_2_, this_.[value_table] as value6_91_2_, sets2_.property_id as property2_55_4_, set3_.id as set1_55_4_, set3_.id as id1_53_0_, set3_.[set_type] as set2_53_0_, set3_.[name] as name3_53_0_, set3_.[description] as description4_53_0_, set3_.parent_set_id as parent5_53_0_, set3_1_.property_id as property2_182_0_, set3_1_.filtered_set_id as filtered3_182_0_, set3_1_.[inclusive] as inclusive4_182_0_, set3_1_.[string_val] as string5_182_0_, set3_1_.[float_val] as float6_182_0_, set3_1_.[date_val] as date7_182_0_, set3_2_.source_id as source2_183_0_, source4_.id as id1_90_1_, source4_.[name] as name2_90_1_, source4_.[description] as description3_90_1_ FROM ahs2_property this_ left outer join  (ahs2_property_set sets2_) on this_.id=sets2_1_.property_id left outer join ahs2_set set3_ on sets2_.set_id=set3_.id left outer join ahs2_filter_set set3_1_ on set3_.id=set3_1_.set_id left outer join ahs2_source_series_type set3_2_ on set3_.id=set3_2_.set_id left outer join ahs2_source source4_ on set3_2_.source_id=source4_.id ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY

   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Criteria.CriteriaLoaderExtensions.LoadAllToList[T](IList`1 loaders, ISessionImplementor session)
   at NHibernate.Impl.SessionImpl.List[T](CriteriaImpl criteria)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at NHibernate.Impl.CriteriaImpl.List()
   at Admc.Data.MappingsTests.EntityTest(KeyValuePair`2 entry) in C:\anna\git\admc35_ahsdev_vs2022\Admc.Data.Tests\MappingsTests.cs:line 65
--SqlException
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)

NHibernate: 
    SELECT
        this_.id as id1_91_2_,
        this_.[type] as type2_91_2_,
        this_.[name] as name3_91_2_,
        this_.[data_type] as data4_91_2_,
        this_.[is_vector] as is5_91_2_,
        this_.[value_table] as value6_91_2_,
        sets2_.property_id as property2_55_4_,
        set3_.id as set1_55_4_,
        set3_.id as id1_53_0_,
        set3_.[set_type] as set2_53_0_,
        set3_.[name] as name3_53_0_,
        set3_.[description] as description4_53_0_,
        set3_.parent_set_id as parent5_53_0_,
        set3_1_.property_id as property2_182_0_,
        set3_1_.filtered_set_id as filtered3_182_0_,
        set3_1_.[inclusive] as inclusive4_182_0_,
        set3_1_.[string_val] as string5_182_0_,
        set3_1_.[float_val] as float6_182_0_,
        set3_1_.[date_val] as date7_182_0_,
        set3_2_.source_id as source2_183_0_,
        source4_.id as id1_90_1_,
        source4_.[name] as name2_90_1_,
        source4_.[description] as description3_90_1_ 
    FROM
        ahs2_property this_ 
    left outer join
        (
            ahs2_property_set sets2_
        ) 
            on this_.id=sets2_1_.property_id 
    left outer join
        ahs2_set set3_ 
            on sets2_.set_id=set3_.id 
    left outer join
        ahs2_filter_set set3_1_ 
            on set3_.id=set3_1_.set_id 
    left outer join
        ahs2_source_series_type set3_2_ 
            on set3_.id=set3_2_.set_id 
    left outer join
        ahs2_source source4_ 
            on set3_2_.source_id=source4_.id 
    ORDER BY
        CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY;
    @p0 = 1 [Type: Int32 (0:0:0)]
4922 [NonParallelWorker] ERROR NHibernate.AdoNet.AbstractBatcher (null) - Could not execute query: SELECT this_.id as id1_91_2_, this_.[type] as type2_91_2_, this_.[name] as name3_91_2_, this_.[data_type] as data4_91_2_, this_.[is_vector] as is5_91_2_, this_.[value_table] as value6_91_2_, sets2_.property_id as property2_55_4_, set3_.id as set1_55_4_, set3_.id as id1_53_0_, set3_.[set_type] as set2_53_0_, set3_.[name] as name3_53_0_, set3_.[description] as description4_53_0_, set3_.parent_set_id as parent5_53_0_, set3_1_.property_id as property2_182_0_, set3_1_.filtered_set_id as filtered3_182_0_, set3_1_.[inclusive] as inclusive4_182_0_, set3_1_.[string_val] as string5_182_0_, set3_1_.[float_val] as float6_182_0_, set3_1_.[date_val] as date7_182_0_, set3_2_.source_id as source2_183_0_, source4_.id as id1_90_1_, source4_.[name] as name2_90_1_, source4_.[description] as description3_90_1_ FROM ahs2_property this_ left outer join  (ahs2_property_set sets2_) on this_.id=sets2_1_.property_id left outer join ahs2_set set3_ on sets2_.set_id=set3_.id left outer join ahs2_filter_set set3_1_ on set3_.id=set3_1_.set_id left outer join ahs2_source_series_type set3_2_ on set3_.id=set3_2_.set_id left outer join ahs2_source source4_ on set3_2_.source_id=source4_.id ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4922 [NonParallelWorker] ERROR NHibernate.AdoNet.AbstractBatcher (null) - Could not execute query: SELECT this_.id as id1_91_2_, this_.[type] as type2_91_2_, this_.[name] as name3_91_2_, this_.[data_type] as data4_91_2_, this_.[is_vector] as is5_91_2_, this_.[value_table] as value6_91_2_, sets2_.property_id as property2_55_4_, set3_.id as set1_55_4_, set3_.id as id1_53_0_, set3_.[set_type] as set2_53_0_, set3_.[name] as name3_53_0_, set3_.[description] as description4_53_0_, set3_.parent_set_id as parent5_53_0_, set3_1_.property_id as property2_182_0_, set3_1_.filtered_set_id as filtered3_182_0_, set3_1_.[inclusive] as inclusive4_182_0_, set3_1_.[string_val] as string5_182_0_, set3_1_.[float_val] as float6_182_0_, set3_1_.[date_val] as date7_182_0_, set3_2_.source_id as source2_183_0_, source4_.id as id1_90_1_, source4_.[name] as name2_90_1_, source4_.[description] as description3_90_1_ FROM ahs2_property this_ left outer join  (ahs2_property_set sets2_) on this_.id=sets2_1_.property_id left outer join ahs2_set set3_ on sets2_.set_id=set3_.id left outer join ahs2_filter_set set3_1_ on set3_.id=set3_1_.set_id left outer join ahs2_source_series_type set3_2_ on set3_.id=set3_2_.set_id left outer join ahs2_source source4_ on set3_2_.source_id=source4_.id ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST @p0 ROWS ONLY
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4989 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4989 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4989 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
4989 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
4995 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4995 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4995 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
4995 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
4996 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4996 [NonParallelWorker] WARN NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at NHibernate.AdoNet.AbstractBatcher.DoExecuteReader(DbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
ClientConnectionId:f37c84c2-2239-4b17-838f-ea59218221e0
Error Number:102,State:1,Class:15
4996 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.
4996 [NonParallelWorker] ERROR NHibernate.Util.ADOExceptionReporter (null) - Incorrect syntax near ')'.
Invalid usage of the option FIRST in the FETCH statement.
Statement(s) could not be prepared.

The output has reached the limit and was truncated.
To view the full output use 'Show Stack Trace in a new window' action.

===========================================

Thanks a lot for reading! I'm very grateful for any ideas on this problem :-)

Best regards, Thomas.

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #3239

Regression made by #2680

### CODE REVIEW

File: src/NHibernate/Engine/TableGroupJoinHelper.cs [hunk 1]
```diff
@@ -68,14 +68,15 @@ private static bool NeedsTableGroupJoin(IReadOnlyList<IJoin> joins, SqlString[]
...
 				if (entityPersister?.HasSubclassJoins(includeSubclasses && isSubclassIncluded(join.Alias)) != true)
 					continue;
 
 				if (hasWithClause)
 					return true;
 
-				if (entityPersister.ColumnsDependOnSubclassJoins(join.RHSColumns))
+				if (collection?.IsManyToMany != true // many-to-many keys are stored in separate table
+				    && entityPersister.ColumnsDependOnSubclassJoins(join.RHSColumns))
 					return true;
```
Comment (hazzik) [inline src/NHibernate/Engine/TableGroupJoinHelper.cs:80]: Please add braces here as it is hard to read now.

File: src/NHibernate/Engine/TableGroupJoinHelper.cs [hunk 2]
```diff
@@ -68,14 +68,15 @@ private static bool NeedsTableGroupJoin(IReadOnlyList<IJoin> joins, SqlString[]
 
 			foreach (var join in joins)
 			{
-				var entityPersister = GetEntityPersister(join.Joinable);
+				var entityPersister = GetEntityPersister(join.Joinable, out var collection);
```
Comment (hazzik) [inline src/NHibernate/Engine/TableGroupJoinHelper.cs:71]: Maybe it is better to return `isManyToMany` as a second parameter here?

Comment (bahusoid) [reply src/NHibernate/Engine/TableGroupJoinHelper.cs]: Ok

File: src/NHibernate/Engine/TableGroupJoinHelper.cs (hunk 1 above)
Comment (bahusoid) [reply src/NHibernate/Engine/TableGroupJoinHelper.cs:80]: Where exactly? Is it still valid?

Comment (hazzik) [reply src/NHibernate/Engine/TableGroupJoinHelper.cs:80]: Yes, still valid. Around `return true;`
```suggestion
				{
					return true;
				}
```

**Review by hazzik — APPROVED** [review]
