### PR TITLE
Fix #1419 - ISession.IsDirty() shouldn't throw exception for transient many-to-one object in a session

### LINKED ISSUE #1419: ISession.IsDirty() shouldn't throw exception for transient many-to-one object in a session
As suggested in https://github.com/nhibernate/nhibernate-core/issues/1413#issuecomment-341455364
I extracted separate issues.

**Current behavior:** TransientObjectException is thrown by ISession.IsDirty() call  when transient many-to-one object is present in session
**Expected behavior:** ISession.IsDirty() should not throw exception

Technical details of the problem is [here](https://github.com/nhibernate/nhibernate-core/issues/1413#issuecomment-341442122).

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #1419

### CODE REVIEW

File: src/NHibernate/Type/ManyToOneType.cs [hunk 1]
```diff
@@ -224,5 +204,31 @@ public override bool[] ToColumnNullness(object value, IMapping mapping)
...
+			{
+				return false;
+			}
+
+			if (old == null || current == null)
+			{
+				return true;
+			}
+
+			if (ForeignKeys.IsTransientFast(GetAssociatedEntityName(), current, session) == true)
```
Comment (fredericDelaporte) [inline src/NHibernate/Type/ManyToOneType.cs]: Need to use `IsTransientSlow`, otherwise the bug will still be there for entities having an assigned id already assigned or having an `unsaved-value` set as `undefined`. `IsTransientSlow` hits the db only if `IsTransientFast` was not able of answering, which occurs in aforementioned cases.

Comment (fredericDelaporte) [inline src/NHibernate/Type/ManyToOneType.cs]: Need to use `IsTransientSlow`, otherwise the bug will still be there for entities having an assigned id already assigned or having an `unsaved-value` set as `undefined`. `IsTransientSlow` hits the db only if `IsTransientFast` was not able of answering, which occurs in aforementioned cases.

Comment (hazzik) [reply src/NHibernate/Type/ManyToOneType.cs]: Need to have a test for this case.

Comment (hazzik) [reply src/NHibernate/Type/ManyToOneType.cs]: @fredericDelaporte, the `GetEntityIdentifierIfNotUnsaved` calls `IsTransientFast` as well.

Comment (hazzik) [reply src/NHibernate/Type/ManyToOneType.cs]: Ok, what will happen in case of an entity with assigned ID - the "IsDirty" method will not fail, but it will return `false`.

Comment (bahusoid) [reply src/NHibernate/Type/ManyToOneType.cs]: @fredericDelaporte 
>Need to use IsTransientSlow, otherwise the bug will still be there
I simply reused check that lead to exception:
https://github.com/nhibernate/nhibernate-core/blob/a6f97d0423b3a57a74e736e9447ca1d0cbb91e88/src/NHibernate/Engine/ForeignKeys.cs#L250-L265

So exception won't be thrown by GetIdentifier method.

@hazzik 
> the "IsDirty" method will not fail, but it will return false

Why false? What IsDirty returns depends on `identifierType.IsDirty` call. And from my understanding it should work fine - we will simply check if identifier value is changed. And if it's new object - it should definitely change.

Comment (bahusoid) [reply src/NHibernate/Type/ManyToOneType.cs]: Just in case I made a quick test with assigned id and it works OK. Should I squash it in to test commit?

**Comment by bahusoid** [comment]
Added new test as separate commit. Let me know if it needs to be rebased and squashed instead.

File: src/NHibernate/Type/ManyToOneType.cs (hunk 1 above)
Comment (fredericDelaporte) [reply src/NHibernate/Type/ManyToOneType.cs]: Yes, better add it to test commit. You may first add it as a "fixup! Test case for GH1419 (ISession.IsDirty() failed for transient many-to-one" commit and later squash it if you prefer.

Well, already added, never minde, can still be squashed later.

> Ok, what will happen in case of an entity with assigned ID - the "IsDirty" method will not fail, but it will return false.

I believe it yields `null` instead in that case, but @bahusoid test seems to show I were wrong in assuming the whole case would fail. Adding tests for assigned id and unsaved-value "undefined" is definitely the way to go.

Comment (hazzik) [reply src/NHibernate/Type/ManyToOneType.cs]: I was checking with Assigned Guids. Not sure why it works with integers.

Comment (bahusoid) [reply src/NHibernate/Type/ManyToOneType.cs]: @hazzik I changed int to Guid in my test and it still works...

Comment (hazzik) [reply src/NHibernate/Type/ManyToOneType.cs]: Maybe I had the same problem ;)

**Comment by hazzik** [comment]
Thanks. Nice work
