### PR TITLE
Fix Criteria with clause for many-to-many

### LINKED ISSUE #1263: NH-2991 - Criteria withClause doesn't work in case of many to many collections
**Mihai Marandici** created an [issue](https://nhibernate.jira.com/browse/NH-2991) — <time datetime="2012-01-05T08:43:18.761Z" title="2012-01-05T08:43:18.761Z">5th January 2012, 8:43:18</time>:
> Creating an alias on a many to many collection using withClause, generates incorrect sql (adds withClause to both joins - many to many table and actual table)
> 
---
**Mihai Marandici** added a comment — <time datetime="2012-01-05T09:07:51.415Z" title="2012-01-05T09:07:51.415Z">5th January 2012, 9:07:51</time>:
> fixed issue with test case
> 
---
**Greg Borota** added a comment — <time datetime="2012-05-03T19:08:05.930Z" title="2012-05-03T19:08:05.930Z">3rd May 2012, 19:08:05</time>:
> This is a major/ugly bug, supprised there is no more noice about fixing it.
>

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #1263

### CODE REVIEW

File: src/NHibernate/Loader/JoinWalker.cs [hunk 1]
```diff
@@ -168,6 +168,7 @@ protected virtual SqlString GetWithClause(string path, string pathAlias)
 			IJoinable joinable = type.GetAssociatedJoinable(Factory);
 
 			string subalias = GenerateTableAlias(associations.Count + 1, path, subPathAlias, joinable);
+			var qc = joinable.IsCollection ? (IQueryableCollection) joinable : null;
```
Comment (bahusoid) [inline src/NHibernate/Loader/JoinWalker.cs]: This is safe `IQueryableCollection` casting. As it's anyway applied for all collections inside `OuterJoinableAssociation.IsManyToManyWith`
