### PR TITLE
Fix loop detection for associations with fetch="join" mapping

### LINKED ISSUE #2201: Fetch Join generates incorrect SQL joins for the same entity type
Using a Fetch Join mapping for an entity that contains references to entities of the same type results in incorrect joins in SQL query.

For an entity:
```c#
public class Entity
{
	public virtual ulong? EntityId { get; set; }
	public virtual string EntityNumber { get; set; }
	public virtual Entity ReferencedEntity { get; set; }
	public virtual Entity AdditionalEntity { get; set; }
	public virtual Entity SourceEntity { get; set; }
}
```
and mapping:
```c#
mapper.Class<Entity>(m =>
{
	m.Id(c => c.EntityId, id =>
	{
		id.Generator(Generators.Native);
	});
	m.Property(c => c.EntityNumber);
	m.ManyToOne(c => c.ReferencedEntity, p =>
	{
		p.Column("ReferencedEntityId");
		p.Fetch(FetchKind.Join);
	});
	m.ManyToOne(c => c.AdditionalEntity, p =>
	{
		p.Column("AdditionalEntityId");
		p.Fetch(FetchKind.Join);
	});
	m.ManyToOne(c => c.SourceEntity, p =>
	{
		p.Column("SourceEntityId");
		p.Fetch(FetchKind.Join);
	});
});
```
running the following query:
```c#
session
	.QueryOver<Entity>()
	.Where(e => e.EntityId == 1)
	.List();
```
results in an incorrect SQL:
```sql
    SELECT
        this_.EntityId as entityid1_0_3_,
        this_.EntityNumber as entitynumber2_0_3_,
        this_.ReferencedEntityId as referencedentityid3_0_3_,
        this_.AdditionalEntityId as additionalentityid4_0_3_,
        this_.SourceEntityId as sourceentityid5_0_3_,
        entity2_.EntityId as entityid1_0_0_,
        entity2_.EntityNumber as entitynumber2_0_0_,
        entity2_.ReferencedEntityId as referencedentityid3_0_0_,
        entity2_.AdditionalEntityId as additionalentityid4_0_0_,
        entity2_.SourceEntityId as sourceentityid5_0_0_,
        entity3_.EntityId as entityid1_0_1_,
        entity3_.EntityNumber as entitynumber2_0_1_,
        entity3_.ReferencedEntityId as referencedentityid3_0_1_,
        entity3_.AdditionalEntityId as additionalentityid4_0_1_,
        entity3_.SourceEntityId as sourceentityid5_0_1_,
        entity4_.EntityId as entityid1_0_2_,
        entity4_.EntityNumber as entitynumber2_0_2_,
        entity4_.ReferencedEntityId as referencedentityid3_0_2_,
        entity4_.AdditionalEntityId as additionalentityid4_0_2_,
        entity4_.SourceEntityId as sourceentityid5_0_2_ 
    FROM
        Entity this_ 
    left outer join
        Entity entity2_ 
            on this_.ReferencedEntityId=entity2_.EntityId 
    left outer join
        Entity entity3_ 
            on entity2_.AdditionalEntityId=entity3_.EntityId 
    left outer join
        Entity entity4_ 
            on entity3_.SourceEntityId=entity4_.EntityId 
    WHERE
        this_.EntityId = :p0;
```
**entity3_** is joined to **entity2_** and **entity4_** is joined to **entity3_** while both should be joined to **this_** like **entity2_**.

Explicitly fetching referenced entities:
```C#
session
	.QueryOver<Entity>()
	.Where(e => e.EntityId == 1)
	.Fetch(SelectMode.Fetch,
		e => e.ReferencedEntity,
		e => e.AdditionalEntity,
		e => e.SourceEntity)
	.List();
```
adds correct joins to SQL but previous still remain (**entity3_** and **entity4_**):
```sql
    SELECT
        this_.EntityId as entityid1_0_5_,
        this_.EntityNumber as entitynumber2_0_5_,
        this_.ReferencedEntityId as referencedentityid3_0_5_,
        this_.AdditionalEntityId as additionalentityid4_0_5_,
        this_.SourceEntityId as sourceentityid5_0_5_,
        entity2_.EntityId as entityid1_0_0_,
        entity2_.EntityNumber as entitynumber2_0_0_,
        entity2_.ReferencedEntityId as referencedentityid3_0_0_,
        entity2_.AdditionalEntityId as additionalentityid4_0_0_,
        entity2_.SourceEntityId as sourceentityid5_0_0_,
        entity3_.EntityId as entityid1_0_1_,
        entity3_.EntityNumber as entitynumber2_0_1_,
        entity3_.ReferencedEntityId as referencedentityid3_0_1_,
        entity3_.AdditionalEntityId as additionalentityid4_0_1_,
        entity3_.SourceEntityId as sourceentityid5_0_1_,
        entity4_.EntityId as entityid1_0_2_,
        entity4_.EntityNumber as entitynumber2_0_2_,
        entity4_.ReferencedEntityId as referencedentityid3_0_2_,
        entity4_.AdditionalEntityId as additionalentityid4_0_2_,
        entity4_.SourceEntityId as sourceentityid5_0_2_,
        entity5_.EntityId as entityid1_0_3_,
        entity5_.EntityNumber as entitynumber2_0_3_,
        entity5_.ReferencedEntityId as referencedentityid3_0_3_,
        entity5_.AdditionalEntityId as additionalentityid4_0_3_,
        entity5_.SourceEntityId as sourceentityid5_0_3_,
        entity6_.EntityId as entityid1_0_4_,
        entity6_.EntityNumber as entitynumber2_0_4_,
        entity6_.ReferencedEntityId as referencedentityid3_0_4_,
        entity6_.AdditionalEntityId as additionalentityid4_0_4_,
        entity6_.SourceEntityId as sourceentityid5_0_4_ 
    FROM
        Entity this_ 
    left outer join
        Entity entity2_ 
            on this_.ReferencedEntityId=entity2_.EntityId 
    left outer join
        Entity entity3_ 
            on entity2_.AdditionalEntityId=entity3_.EntityId 
    left outer join
        Entity entity4_ 
            on entity3_.SourceEntityId=entity4_.EntityId 
    left outer join
        Entity entity5_ 
            on this_.AdditionalEntityId=entity5_.EntityId 
    left outer join
        Entity entity6_ 
            on this_.SourceEntityId=entity6_.EntityId 
    WHERE
        this_.EntityId = :p0;
```

### PR DESCRIPTION
**Pull request by deAtog**
Fixes  #2201

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
It is usually more efficient to setup your development for running the tests itself, see [contributing (Setting up for development)](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md#setting-up-for-development).

**Comment by deAtog** [comment]
@fredericDelaporte I have a test/debug environment but running the tests locally was taking far more time than the automated build here. I was also getting local failures where there were none on the ci system.

I'm still debating what to do here.. disabling the circular join checks causes undoubtedly causes issues when the max_fetch_depth is unset and in some cases even with it set it still causes problems.

**Comment by deAtog** [comment]
@fredericDelaporte This should address the issue identified in issue #2201 and provide a mechanism for users to disable the loop detection which results in an 1+N case when the entity graph does not have a loop, but the query does. It should be safe for users to disable the loop detection whenever they do not have implicit loops in their entity graph or when they have explicitly set max_fetch_depth.

**Review by bahusoid — CHANGES_REQUESTED** [review]
I will do a proper review when I have time but it looks pretty good at quick glance. Some notes:
You shouldn't delete protected members (`IsJoinable`) - it's a breaking change. Mark it as obsolete instead. And better to get rid of formatting changes in unrelated places.

You disabled in tests loop detection but reported issue is actually related to old loop detection logic. So reported issue is actually not tested. Please add tests to verify that proper entities are initialized when loop detection is enabled.

Use additionally `NHibernateUtil.IsInitialized` in tests to verify that entity is actually initialized. Something like:
```C#
Assert.That(p.Parent.Details, Is.Not.Null);
Assert.That(NHibernateUtil.IsInitialized(p.Parent.Details));
```

**Comment by deAtog** [comment]
@bahusoid With a one-to-one relationship both the old and new behavior always initialize the one-to-one, but they cause additional EntityFetch's to occur.

The changes to the JoinWalker are well tested by every other test in the suite.  A test that verifies the old behavior vs the new behavior would be very similar to those that failed after modifying it. Those tests only passed due to the side affects of the loop detection and depth-first nature of the old JoinWalker. Those tests did the following:
1. Query for a Contract
   a. Contract has fetch="join" set for Subcontracts and Parties
   b. Subcontracts is of type Contract and is initialized before Parties. As a result, Contract.Subcontract.Parties was was being initialized but Contract.Parties was not.
2. Deleted parties for the Contract
3. Deleted the Contract
    a. Deleting a Contract cascade deletes Subcontracts, Parties, and Infos.

After the changes to the JoinWalker, Contract.Subcontract.Parties is not initialized but Contract.Parties is. Attempting to delete the Contract after deleting all Parties threw an exception because the Contract could not cascade delete the Parties that were associated with it. If these tests had originally asserted that Contracts.Parties was initialized they would have failed. 

Swapping steps 1 and 2 above, ensures that the loaded Contract does not have any Parties associated with it and the deletion of the Contract succeeds without issue.

**Comment by deAtog** [comment]
@bahusoid I'm going to re-order/combine these commits to make it easier to review. I'll let you know when it is ready again. The recent commits revert some of the original modifications to JoinWalker to avoid using the queue for anything but required joins. This eliminates the overhead involved in the simplest of cases where no joins are present.

**Comment by hazzik** [comment]
@bahusoid  could you please take another look? It seems the changes you've requested are implemented now.

**Comment by bahusoid** [comment]
Pretty busy IRL right now - no time for proper reviews (maybe in June). But at really quick glance I still see no tests to verify that #2201 is actually fixed. Also it seems `currentDetph` calculation is broken for entity joins - so we also need test that verifies proper eager child loading for entity join when max_fetch_depth set to 1

File: src/NHibernate/Loader/JoinWalker.cs [hunk 1]
```diff
@@ -299,26 +312,48 @@ private void AddAssociation(OuterJoinableAssociation association)
...
+
+				switch(entry)
+				{
+					case CollectionQueueEntry ce:
+						WalkCollectionTree(ce.Persister, ce.Alias, ce.Path, ce.PathAlias);
+						break;
+					case EntityQueueEntry eqe:
+						WalkEntityTree(eqe.Persister, eqe.Alias, eqe.Path);
+						break;
+					default:
```
Comment (hazzik) [inline src/NHibernate/Loader/JoinWalker.cs:342]: `default` is never reached here. The `QueueEntry` is always either `CollectionQueueEntry` or `EntityQueueEntry`.

Comment (hazzik) [reply src/NHibernate/Loader/JoinWalker.cs:342]: Oh, I see... you enqueue `null` there.

**Review by bahusoid — APPROVED** [review]

**Review by bahusoid — APPROVED** [review]

File: src/NHibernate.Test/NHSpecificTest/GH2201/CircularReferenceFetchDepthFixture.cs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+			//Generate another test entities
+			base.OnSetUp();
+			_id3 = _id;
+			base.OnSetUp();
+		}
+
+		[Test]
+		public void QueryOver()
+		{
+			using(var logSpy = new SqlLogSpy())
```
[the remark this answers is not in the document]
Comment (bahusoid) [reply src/NHibernate.Test/NHSpecificTest/GH2201/CircularReferenceFetchDepthFixture.cs]: Yeap.. Removed

**Review by bahusoid — APPROVED** [review]

**Review by fredericDelaporte — DISMISSED** [review]

File: src/NHibernate/Loader/JoinWalker.cs [hunk 3]
```diff
@@ -1202,5 +1253,53 @@ protected static string GetSelectFragment(OuterJoinableAssociation join, string
 		{
 			return join.GetSelectFragment(entitySuffix, collectionSuffix, next);
 		}
+
+		protected abstract class QueueEntry
```
Comment (hazzik) [inline src/NHibernate/Loader/JoinWalker.cs:1257]: This should be just interface

File: src/NHibernate/Loader/JoinWalker.cs [hunk 4]
```diff
@@ -1202,5 +1253,53 @@ protected static string GetSelectFragment(OuterJoinableAssociation join, string
...
+		{
+			public abstract void Walk(JoinWalker walker);
+		}
+
+		protected abstract class QueueEntry<T> : QueueEntry where T : IJoinable
```
Comment (hazzik) [inline src/NHibernate/Loader/JoinWalker.cs:1262]: There's no usage for this class.

File: src/NHibernate/Loader/JoinWalker.cs [hunk 5]
```diff
@@ -1202,5 +1253,53 @@ protected static string GetSelectFragment(OuterJoinableAssociation join, string
...
+		{
+			public string Alias { get; set; }
+			public T Persister { get; set; }
+		}
+
+		protected abstract class EntityQueueEntry<T> : QueueEntry<T> where T : IJoinable
```
Comment (hazzik) [inline src/NHibernate/Loader/JoinWalker.cs:1268]: There's no usage for this class.

File: src/NHibernate/Loader/JoinWalker.cs [hunk 6]
```diff
@@ -439,31 +461,46 @@ internal OuterJoinableAssociation InitAssociation(OuterJoinableAssociation assoc
 		/// For an entity class, add to a list of associations to be fetched
 		/// by outerjoin
 		/// </summary>
-		protected virtual void WalkEntityTree(IOuterJoinLoadable persister, string alias, string path, int currentDepth)
+		/// Since 5.4
+		protected virtual void WalkEntityTree(IOuterJoinLoadable persister, string alias, string path)
```
Comment (hazzik) [inline src/NHibernate/Loader/JoinWalker.cs:465]: Is this a new method?

**Review by hazzik — DISMISSED** [review]

**Review by bahusoid — DISMISSED** [review]

File: src/NHibernate/Loader/JoinWalker.cs (hunk 6 above)
Comment (bahusoid) [reply src/NHibernate/Loader/JoinWalker.cs:450]: New overload without `currentDepth`. Old one is `Obsolete` now.. `Since...` comment need to be moved to old one...

**Review by bahusoid — APPROVED** [review]
