### PR TITLE
Fix Linq Future aggregates failures, fixes #1387

### LINKED ISSUE #1387: Linq Sum() with ToFutureValue fails
I have the following code to get a sum of values using futures:

```csharp
var sum = s.Query<AnEntity>()
	.Select(x => x.AnInt)
	.ToFutureValue(x => x.Sum());

Assert.NotZero(sum.Value);
```

This fails in NHibernate 5 with the following exception:

```
System.ArgumentException: Object of type 'System.Linq.EnumerableQuery`1[System.Int32]' cannot be converted to object of type 'System.Collections.Generic.IEnumerable`1[System.Nullable`1[System.Int32]]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at NHibernate.Impl.FutureValue`1.get_Value()
```

`s.Query<AnEntity>()` is not empty. Just using `Sum()` without futures works as expected.

I already analyzed this bug and created a pull request where I explain it in more detail: #1388

### PR DESCRIPTION
**Pull request by fredericDelaporte**
This is an alternate fix for #1387, aiming at replacing #1388.

It includes the tests added in #1388, but fix the trouble with another way. It is required for fixing all cases, especially all the NH-3850 tests once rewritten for testing both non-future and future queries.

### CODE REVIEW

File: src/NHibernate/Impl/FutureBatch.cs [hunk 1]
```diff
@@ -80,5 +116,88 @@ private IEnumerable<TResult> GetCurrentResult<TResult>(int currentIndex)
...
+					{
+						results.Add(element);
+					}
+					return results;
+				}
+
+				// When not null on a future value, ExecuteOnEval is fetched with PostExecuteTransformer from
+				// IntermediateHqlTree through ExpressionToHqlTranslationResults, which requires a IQueryable
+				// as input and directly yields the scalar result when the query is scalar.
+				var resultElement = postExecute.ExecuteOnEval.DynamicInvoke(collection.AsQueryable());
```
Comment (fredericDelaporte) [inline src/NHibernate/Impl/FutureBatch.cs]: No need to type the collection for `AsQueryable` if its underlying type is already the good one, which is done in multi-query.

File: src/NHibernate/Impl/MultiQueryImpl.cs [hunk 2]
```diff
@@ -458,30 +458,37 @@ protected void After()
...
-					resultCollections.Add(new List<object>());
-				}
-				else
-				{
-					resultCollections.Add(Activator.CreateInstance(typeof(List<>).MakeGenericType(resultCollectionGenericType[i])));
-				}
+				var query = queries[i] as ExpressionQueryImpl;
+				// Linq queries may override the query type, finishing the work with a post execute transformer,
+				// which with multi queries are executed through the multi-query result trasformer.
+				var rawElementType = query?.QueryExpression?.Type ?? resultCollectionGenericType[i];
```
Comment (fredericDelaporte) [inline src/NHibernate/Impl/MultiQueryImpl.cs]: Grabbing here the Linq result type override if any, for typing the list before transformation with nullable if required.

File: src/NHibernate/Impl/MultiQueryImpl.cs [hunk 3]
```diff
@@ -458,30 +458,37 @@ protected void After()
...
+			}
+
+			var multiqueryHolderInstatiator = GetMultiQueryHolderInstatiator();
+			var resultCollections = new List<object>(resultCollectionGenericType.Count);
+			for (var i = 0; i < queries.Count; i++)
+			{
+				// Once polymorpic queries aggregated in one result per query (previous loop), use the
+				// MultiQueryTransformer using, as source, the aggregated result.
+				var resultList = GetTransformedResults(rawResultCollections[i], multiqueryHolderInstatiator);
+				resultCollections.Add(resultList);
```
Comment (fredericDelaporte) [inline src/NHibernate/Impl/MultiQueryImpl.cs]: We already have a list of target type here, no need to redo list instanciation + `ArrayHelper.AddAll`.

File: src/NHibernate/Impl/FutureBatch.cs [hunk 4]
```diff
@@ -80,5 +116,88 @@ private IEnumerable<TResult> GetCurrentResult<TResult>(int currentIndex)
...
+
+			public IList TransformList(IList collection)
+			{
+				if (_currentIndex >= _postExecutes.Count)
+					throw new InvalidOperationException(
+						$"Transformer have been called more times ({_currentIndex + 1}) than it has queries to transform.");
+
+				var postExecute = _postExecutes[_currentIndex];
+				_currentIndex++;
+				if (postExecute.ExecuteOnEval == null)
```
Comment (hazzik) [inline src/NHibernate/Impl/FutureBatch.cs]: I would like to encapsulate this logic into PostExecute class

Comment (hazzik) [reply src/NHibernate/Impl/FutureBatch.cs]: I’ve made a slight refactoring. I’ll update the branch shortly.

**Comment by hazzik** [comment]
Hi @fredericDelaporte please review my commit, and if it is ok - integrate

File: src/NHibernate/Impl/FutureBatch.cs [hunk 5]
```diff
@@ -154,38 +133,14 @@ public object TransformTuple(object[] tuple, string[] aliases)
...
-				}
-
-				// When not null on a future value, ExecuteOnEval is fetched with PostExecuteTransformer from
-				// IntermediateHqlTree through ExpressionToHqlTranslationResults, which requires a IQueryable
-				// as input and directly yields the scalar result when the query is scalar.
-				var resultElement = postExecute.ExecuteOnEval.DynamicInvoke(collection.AsQueryable());
-				results.Add(resultElement);
 
-				return results;
+				return batchedQuery.Future?.TransformList(collection);
```
Comment (fredericDelaporte) [inline src/NHibernate/Impl/FutureBatch.cs]: In fact I do not think we may have cases where `Future` will be null, but I have not checked all code paths to be sure, so for a patch I have chosen to be on the safe side.
But then we requires here to yield the collection, not `null`.
I will integrate by changing this to:
```c#
return batchedQuery.Future?.TransformList(collection) ?? collection;
```
This may hide/obfuscate a failure case (`TransformList` yielding `null`), but that is a quite unlikely failure.

**Comment by hazzik** [comment]
I reworded the commit messages to make them more natural as we are not dependant on JIRA now. The idea is to mention "Fixes #1387" in a merge commit.

File: src/NHibernate/Impl/MultiQueryImpl.cs [hunk 6]
```diff
@@ -458,58 +458,54 @@ protected void After()
...
+				// Once polymorpic queries aggregated in one result per query (previous loop), use the
+				// MultiQueryTransformer using, as source, the aggregated result.
+				var resultList = GetTransformedResults(rawResultCollections[i]);
+				resultCollections.Add(resultList);
 			}
 
 			return resultCollections;
 		}
 
-		private IList GetTransformedResults(IList source, HolderInstantiator holderInstantiator)
```
Comment (hazzik) [inline src/NHibernate/Impl/MultiQueryImpl.cs]: @fredericDelaporte I've removed HolderInstantiator here as it just adds the overhead without providing much value

File: src/NHibernate/Impl/MultiQueryImpl.cs [hunk 7]
```diff
@@ -458,58 +458,54 @@ protected void After()
...
+		private  IList GetTransformedResults(IList source)
 		{
-			if (!holderInstantiator.IsRequired)
-			{
+			if (resultTransformer == null)
 				return source;
-			}
-			for (int j = 0; j < source.Count; j++)
+
+			//MultiCriteria does not call TransformTuple here
```
Comment (fredericDelaporte) [inline src/NHibernate/Impl/MultiQueryImpl.cs]: MultiCriteria and MultiQuery looks as almost dups which have diverged on some points. Probably we need the issue on having a common query interface to be done for refactoring this.

Comment (hazzik) [reply src/NHibernate/Impl/MultiQueryImpl.cs]: It's in #792

File: src/NHibernate/Impl/FutureBatch.cs [hunk 8]
```diff
@@ -80,5 +116,88 @@ private IEnumerable<TResult> GetCurrentResult<TResult>(int currentIndex)
...
+			public System.Type ResultType { get; set; }
+			public Delegate ExecuteOnEval { get; set; }
+			public bool IsValue { get; set; }
+		}
+
+		// ResultTransformer are usually re-usable, this is not the case of this one, which will
+		// be built for each multi-query requiring it.
+		// It also usually ends in query cache, but this is not the case either for multi-query.
+		[Serializable]
+		private class FutureResultsTransformer : IResultTransformer
```
[the remark this answers is not in the document]
Comment (ngbrown) [reply src/NHibernate/Impl/FutureBatch.cs]: Since `FutureResultsTransformer` isn't actually serializable because `BatchedQuery` isn't serializable, can the test in `DetachedCriteriaSerializable` be adjusted to exclude this type instead?  `DetachedCriteria` doesn't expose a `Future`, so not all `IResultTransformer` technically need to be serializable.

Why is serializing a `DetachedCriteria` so important anyway?

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate/Impl/FutureBatch.cs]: Originally I have made that class truly serializable, but that was requiring an additional "data holding" class just for that.

We could instead try to adjust the serializable test, but since this class is private, we will have to add some more reflection logic matching by name to do so. Does that `Serializable` attribute hurts somewhere that it would be better to remove it?

About `DetachedCriteria`, I have not checked why it actually needs to be serializable, but I think it is likely because it may ends in the query cache too.

[the remark this answers is not in the document]
Comment (ngbrown) [reply src/NHibernate/Impl/FutureBatch.cs]: Since serialization is the biggest compatibility break with .NET Core, I am writing some Roslyn analyzers to find issues so I can try to resolve them ahead of time.  On types that are required to be serialized for some reason, and use `Type` or `MethodInfo`, etc., I'll probably have to implement `ISerializable`.

Of course this `FutureResultsTransformer ` is triggering a full-framework warning which is based on FxCop rule [CA2235](https://docs.microsoft.com/visualstudio/code-quality/ca2235-mark-all-non-serializable-fields).  Marking the field as `[NonSerializable]` is really just masking the problem because the entire type wouldn't work if it were deserialized like that.

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate/Impl/FutureBatch.cs]: It seems to me most of those `Serializable` things everywhere in NHibernate code are here for allowing to serialize sessions and session factories. But is there any practical common use case in serializing sessions? Do a significant parts of NHibernate user need this?

Maybe should we consider dropping the possibility of serializing sessions and session factories.

[the remark this answers is not in the document]
Comment (fredericDelaporte) [reply src/NHibernate/Impl/FutureBatch.cs]: I found [this](https://nhibernate.jira.com/browse/NH-3487), which shows there are users using session serialization. It looks like we need to keep that.
