### PR TITLE
Fix HQL and LINQ query by a type on <any/> with meta-types other than int

### LINKED ISSUE #1774: HQL and LINQ query by the type on <any/> with meta-type "string" fails
HQL and LINQ query by **the type** on `<any/>` with `meta-type="string"` fails with `System.Data.SqlClient.SqlException : Invalid column name`. Looks like **the type** makes into SQL query text without single quotes.

To replicate the issue, follow the steps:

1. Map using `<any/>` with `meta-type="string"`:

>   <class name="ToyBox">
    <id name="Id">
      <generator class="native"/>
    </id>
    <property name="Name" />
    <any name="Shape" id-type="int" meta-type="string">
      <meta-value value="CircleType" class="Circle"/>
      <meta-value value="SquareType" class="Square"/>
      <column name="ShapeType" />
      <column name="ShapeId" />
    </any>
  </class>

2. Try to query **by type** using HQL:

`  var boxes = 	s.CreateQuery("from ToyBox t where t.Shape.class = Square").List<ToyBox>();`

or LINQ:

```
var boxes =
	(from t in s.Query<ToyBox>()
		where t.Shape is Square
		select t).ToList();
```

3. The Query will fail witch exception:

> NHibernate.Exceptions.GenericADOException : could not execute query
[ select toybox0_.Id as id1_0_, toybox0_.Name as name2_0_, toybox0_.ShapeType as shapetype3_0_, toybox0_.ShapeId as shapeid4_0_ from ToyBox toybox0_ where toybox0_.ShapeType=SquareType ]
[SQL: select toybox0_.Id as id1_0_, toybox0_.Name as name2_0_, toybox0_.ShapeType as shapetype3_0_, toybox0_.ShapeId as shapeid4_0_ from ToyBox toybox0_ where toybox0_.ShapeType=SquareType]
  ----> System.Data.SqlClient.SqlException : Invalid column name 'SquareType'.
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List[T](IQueryExpression query, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List[T]()
   at NHibernate.Test.NHSpecificTest.GHHQL.Fixture.AnyIs_HqlWithClassNameInTheRight()

There are related issues fixed in a past: [NH-2741](https://nhibernate.jira.com/browse/NH-2741), [NH-2328](https://nhibernate.jira.com/browse/NH-2328), [NH-3251](https://nhibernate.jira.com/browse/NH-3251). The issue NH-2328 has an unit test (NHibernate.Test.NHSpecificTest.NH2328) that demonstrates query by the type on `<any/>` with meta-type "**int**". The unit test successfully passes. However if we change mapping from meta-type "**int**" to meta-type "**string**", the test will fail.

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #1774

### CODE REVIEW

File: src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs [hunk 1]
```diff
@@ -277,25 +278,29 @@ private void ProcessMetaTypeDiscriminatorIfNecessary(IASTNode lhs, IASTNode rhs)
 				return;
 			}
 
-			var lhsNodeMetaType = lhsNode.DataType as MetaType;
-			if (lhsNodeMetaType != null)
+			if (lhsNode.DataType is MetaType lhsNodeMetaType)
```
Comment (fredericDelaporte) [inline src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs]: Having a quick look at it, it seems the same could be done with `ClassMetaType`, which should allow supporting the `Class` mapping case. Or am I missing something?
(Maybe `ClassMetaType` should even extend `MetaType`, with a hard-coded in base constructor call `StringType` base type.)

Comment (fredericDelaporte) [reply src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs]: Well, the HQL test is invalid for that case, because `class` meta-type asks for the full class name.

By the way there is a workaround for all HQL cases: using parameters. It seems this was considered as a known limitation of the `any` mapping at some point, see [this Jira comment](https://nhibernate.jira.com/browse/NH-1403?focusedCommentId=16651&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16651).

**Comment by hazzik** [comment]
@fredericDelaporte I think here we shall fix only what's been asked for (meta-type). Rest can be fixed later at some point, if we'll desire to do so.

**Comment by hazzik** [comment]
Gave it another try and I was able to make it work with for `meta-type="class"`

**Comment by fredericDelaporte** [comment]
Great. I was still looking in all this.

Currently, "implicit" is in fact equivalent to `meta-type="string"` without any meta-value specified. Not having meta-values with a basic type is normally an error (at least that is the way I have documented it, and it now appears to me I have to review that part of the doc again).
But it was previously resolving to `TypeType`, which was equivalent to `class`. So indeed, things are a bit messy currently about the `any` type.

**Comment by hazzik** [comment]
Ok, this broke an old test.
